#!/usr/bin/env python3
"""Apply manually reviewed translations left after the official-source import."""

from __future__ import annotations

import json
import re
import zipfile
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "overrides/kubejs/assets"
PLACEHOLDER_RE = re.compile(r"%(?:\d+\$)?([a-zA-Z%])")

MANUAL = {
    "ae2": {
        "ae2.rei_jei_integration.flowing_fluid_name": "%s (течение)",
        "ae2.rei_jei_integration.silk_touch_causes_less_decay": "«Шёлковое касание» уменьшает распад",
        "ae2.rei_jei_integration.spatial_io_causes_none": "Пространственный ввод-вывод не вызывает распада",
        "chat.ae2.ChannelModeCurrent": "Текущий режим каналов: %s",
        "chat.ae2.TestWorldNotInSuperflatVoid": "Тестовый мир можно создать только в плоском мире с шаблоном «Пустота»!",
        "gui.ae2.SearchSettingsSearchTooltips": "Искать в подсказках",
        "gui.ae2.SearchTooltipIncludingTooltips": "Искать в названиях и подсказках",
        "gui.ae2.units.rf": "RF",
        "gui.tooltips.ae2.ShowAll": "Показать всё",
        "gui.tooltips.ae2.ShowFluidsOnly": "Показать только жидкости",
        "gui.tooltips.ae2.ShowItemsOnly": "Показать только предметы",
    },
    "quark": {
        "quark.jei.hint.echorang": "Эхоранг действует как пикаранг, но постоянно создаёт вибрации и летит дольше, если слышит скалк-крикуна.",
        "quark.jei.hint.gold_tool_fortune": "Золотые инструменты имеют встроенные чары «Удача %s» или эффект «Добыча». Они не складываются с наложенными чарами: применяется только самый высокий уровень.",
        "quark.jei.hint.head_sfx": "Голову любого монстра можно установить сбоку от нотного блока: при получении сигнала он воспроизведёт звук этого монстра.",
        "quark.jei.hint.minecraft.jukebox": "Используйте раздатчик, чтобы автоматически вставлять пластинки в проигрыватель.",
        "quark.jei.hint.pink_blossom_sapling": "Можно найти в горах.",
        "quark.jei.hint.runes": "Объедините руну с зачарованным предметом на наковальне, чтобы изменить цвет его блеска. Это только визуальный эффект.",
        "quark.jei.hint_preamble": "[Quark]\n",
        "tag.item.quark.runes": "Руны",
        "tag.item.quark.runes_lootable": "Руны в добыче",
    },
    "compactmachines": {
        "advancement.compactmachines.claimed_machine_giant": "Здесь хватит места?",
        "advancement.compactmachines.claimed_machine_giant.desc": "Привяжите гигантскую компактную машину.",
        "advancement.compactmachines.claimed_machine_large": "Есть куда расти",
        "advancement.compactmachines.claimed_machine_large.desc": "Привяжите большую компактную машину.",
        "advancement.compactmachines.claimed_machine_max": "Место для всего!",
        "advancement.compactmachines.claimed_machine_max.desc": "Привяжите максимальную компактную машину.",
        "advancement.compactmachines.claimed_machine_normal": "Внутри больше, чем снаружи",
        "advancement.compactmachines.claimed_machine_normal.desc": "Привяжите обычную компактную машину.",
        "advancement.compactmachines.claimed_machine_small": "Уже можно дышать",
        "advancement.compactmachines.claimed_machine_small.desc": "Привяжите малую компактную машину.",
        "advancement.compactmachines.claimed_machine_tiny": "Мало места — много идей",
        "advancement.compactmachines.claimed_machine_tiny.desc": "Привяжите крошечную компактную машину.",
        "command.compactmachines.cannot_give_machine_item": "Не удалось выдать игроку новую машину.",
        "command.compactmachines.failed_command_file_error": "Не удалось выполнить команду из-за ошибки файла. Проверьте журнал.",
        "command.compactmachines.level_not_found": "Измерение компактных машин не найдено.",
        "command.compactmachines.level_registered": "Измерение компактных машин найдено.",
        "command.compactmachines.machine_given_successfully": "Новая машина создана и выдана игроку %s.",
        "command.compactmachines.machine_not_bound": "Машина в точке %s не привязана к комнате.",
        "command.compactmachines.not_in_compact_dim": "Эту команду можно использовать только внутри комнаты машины.",
        "command.compactmachines.room_not_found": "Комната [%s] не найдена.",
        "command.compactmachines.room_reg_count": "Зарегистрировано комнат: %s",
        "command.compactmachines.spawn_changed_successfully": "Точка возрождения комнаты [%s] изменена.",
        "command.compactmachines.summary.machines.dimension": "[%s]: %s",
        "command.compactmachines.summary.machines.total": "Всего: %s",
        "death.attack.compactmachines_voidair": "%1$s не удалось войти в пустоту",
        "message.compactmachines.cannot_rename_not_owner": "Только %s может переименовать эту комнату.",
        "message.compactmachines.how_did_you_get_here": "Как ты сюда попал?!",
        "message.compactmachines.machine_room_info": "Машина в точке %1$s привязана к комнате размера «%2$s» в точке %3$s",
        "message.compactmachines.new_machine": "Новая машина",
        "message.compactmachines.no_available_sides": "Для туннеля этого типа нет свободных сторон.",
        "message.compactmachines.not_the_room_owner": "Вы не владелец комнаты; изменять её может только %s.",
        "message.compactmachines.player_room_info": "Игрок «%1$s» находится в комнате размера «%3$s» в точке %2$s.",
        "message.compactmachines.teleport_oob": "Потусторонняя сила мешает телепортации.",
        "message.compactmachines.unknown_room_chunk": "Неизвестная комната в точке %s; проверьте, существует ли она.",
        "message.compactmachines.upgrade_add_failed": "Не удалось применить улучшение к комнате.",
        "message.compactmachines.upgrade_already_present": "Это улучшение уже применено к комнате.",
        "message.compactmachines.upgrade_applied": "Улучшение применено к комнате.",
        "message.compactmachines.upgrade_not_present": "Это улучшение не применено к комнате.",
        "message.compactmachines.upgrade_remove_failed": "Не удалось снять улучшение с комнаты.",
        "message.compactmachines.upgrade_removed": "Улучшение снято с комнаты.",
        "tooltip.compactmachines.machine.bound_to": "Привязана к: %1$s",
        "tooltip.compactmachines.room_name": "Привязана к комнате: %s",
        "tooltip.compactmachines.room_upgrade_type": "Тип: %s",
        "tooltip.compactmachines.tutorial_apply_room_upgrade": "Используйте на привязанном блоке машины, чтобы применить улучшение.",
    },
    "ftbchunks": {
        "ftbchunks.chunk_load_offline": "Разрешить принудительную загрузку для игроков не в сети",
        "ftbchunks.chunk_load_offline.tooltip": "Резервное правило загрузки чанков, когда\n«Режим принудительной загрузки» установлен в значение «По умолчанию»",
        "ftbchunks.claim_dimension_blacklist.tooltip": "Список идентификаторов измерений, где нельзя захватывать чанки.\nНапример, добавьте в список \"minecraft:the_end\", чтобы запретить захват чанков в Краю.\nПоддерживаются шаблоны: \"othermod:*\" соответствует всем измерениям мода \"othermod\".",
        "ftbchunks.claim_dimension_whitelist.tooltip": "Список идентификаторов измерений, где можно захватывать чанки. Если список не пуст, измерение должно находиться в нём и отсутствовать в чёрном списке.\nСинтаксис такой же, как у чёрного списка измерений.",
        "ftbchunks.disable_protection.tooltip": "Подходит для частных серверов, где все доверяют друг другу,\nа захваты нужны только для принудительной загрузки чанков.",
        "ftbchunks.experimental_performance_improvement": "Экспериментальное повышение производительности",
        "ftbchunks.force_load_mode": "Режим принудительной загрузки",
        "ftbchunks.force_load_mode.tooltip": "НИКОГДА: разрешать принудительную загрузку, только если хотя бы один игрок команды в сети.\nВСЕГДА: разрешать её, даже когда все игроки не в сети.\nПО УМОЛЧАНИЮ: разрешать, ЕСЛИ хотя бы у одного игрока команды есть право FTB Ranks «ftbchunks.chunk_load_offline»\nИЛИ включён параметр «Разрешить принудительную загрузку для игроков не в сети».",
        "ftbchunks.long_range_tracker_interval.tooltip": "Интервал в тиках между отправкой клиентам данных отслеживания игроков на большом расстоянии.\nМеньшие значения дают более частые обновления, но повышают нагрузку на сервер и сеть;\nбудьте осторожны, особенно на загруженных серверах.\nЗначение 0 отключает отслеживание на большом расстоянии.",
        "ftbchunks.max_force_loaded_chunks": "Максимум принудительно загруженных чанков на игрока",
        "ftbchunks.max_idle_days_before_unclaim.tooltip": "Если никто из команды не входит в игру столько дней,\nзахваты команды будут освобождены.\nЗначение 0 отключает автоматическое освобождение.",
        "ftbchunks.max_idle_days_before_unforce.tooltip": "Если никто из команды не входит в игру столько дней,\nчанки команды перестанут загружаться принудительно.\nЗначение 0 отключает автоматическое снятие принудительной загрузки.",
        "ftbchunks.minimap.entity_heads": "Головы существ",
        "ftbchunks.minimap.player_heads": "Головы игроков",
        "ftbchunks.minimap.proportional.tooltip": "Если включено, размер мини-карты равен 10%% ширины экрана с учётом настройки масштаба.\nЕсли выключено, размер фиксирован и не зависит от разрешения экрана.",
        "ftbchunks.minimap.visibility": "Видимость",
        "ftbchunks.minimap.xyz": "XYZ",
        "ftbchunks.no_wilderness.tooltip": "Если включено, изменять можно только заранее захваченные чанки.\nПереопределяет параметр «Защищать незахваченные области по измерениям».",
        "ftbchunks.waypoint_dot_fade_distance": "Точки меток: начало затухания",
        "ftbchunks.waypoint_fade_distance": "Маяки меток: начало затухания",
        "ftbchunks.waypoint_max_distance": "Метки: максимальная дальность отображения",
    },
    "extendedcrafting": {
        "book.extendedcrafting.entry.flux_crafting.page.1": "Флаксовый крафт использует и силу ожидания, и энергию. Установка состоит из флаксового верстака и флаксовых альтернаторов. Верстак получает энергию от альтернаторов: чем их больше, тем быстрее идёт крафт.",
        "book.extendedcrafting.entry.flux_crafting.page.2": "Флаксовые альтернаторы можно размещать вокруг флаксового верстака в $(bold)радиусе 3 блоков$() — даже над ним или под ним!",
        "config.jade.plugin_extendedcrafting.advanced_auto_table": "Сведения об улучшенном автоматическом верстаке",
        "config.jade.plugin_extendedcrafting.advanced_table": "Сведения об улучшенном верстаке",
        "config.jade.plugin_extendedcrafting.auto_ender_crafter": "Сведения об автоматическом эндер-верстаке",
        "config.jade.plugin_extendedcrafting.basic_auto_table": "Сведения о базовом автоматическом верстаке",
        "config.jade.plugin_extendedcrafting.basic_table": "Сведения о базовом верстаке",
        "config.jade.plugin_extendedcrafting.compressor": "Сведения о квантовом компрессоре",
        "config.jade.plugin_extendedcrafting.crafting_core": "Сведения о ядре крафта",
        "config.jade.plugin_extendedcrafting.elite_auto_table": "Сведения об элитном автоматическом верстаке",
        "config.jade.plugin_extendedcrafting.elite_table": "Сведения об элитном верстаке",
        "config.jade.plugin_extendedcrafting.ender_crafter": "Сведения об эндер-верстаке",
        "config.jade.plugin_extendedcrafting.pedestal": "Сведения о пьедестале",
        "config.jade.plugin_extendedcrafting.ultimate_auto_table": "Сведения о предельном автоматическом верстаке",
        "config.jade.plugin_extendedcrafting.ultimate_table": "Сведения о предельном верстаке",
        "tooltip.extendedcrafting.and_x_more": "И ещё %s…",
        "tooltip.extendedcrafting.auto_table_delete_recipe": "Shift + ЛКМ, чтобы удалить этот рецепт.",
        "tooltip.extendedcrafting.auto_table_save_recipe": "Shift + ЛКМ, чтобы сохранить этот рецепт.",
        "tooltip.extendedcrafting.per_alternator": "%s на альтернатор",
        "tooltip.extendedcrafting.seconds": "%s с",
        "tooltip.extendedcrafting.selected": "Выбрано",
    },
    "supplementaries": {
        "filled_map.sliced.tooltip": "Фрагмент: %d",
        "globe.supplementaries.sun": "Солнце",
        "gui.supplementaries.optifine.message": "Прежде чем продолжить, учтите: OptiFine часто вызывает ошибки и вылеты.\n\nЭтот мод плохо подходит для сборок и неоднократно проявлял серьёзную несовместимость даже с самим Forge.\n\nКроме того, существуют гораздо более производительные альтернативы: ModernFix, Embeddium, а для шейдеров — Oculus.\n\nИ в сборках, и в обычной игре рекомендуем использовать перечисленные ниже моды.",
        "gui.supplementaries.optifine.suggestions": "Вместо него рекомендуем следующие моды.",
        "gui.supplementaries.optifine.title": "ВНИМАНИЕ: ОБНАРУЖЕН OPTIFINE",
        "gui.supplementaries.optifine.turn_off": "Больше не показывать",
        "leaves_type.twilightforest.dark": "Тёмное дерево",
        "leaves_type.ulterlands.souldrained": "Окаменевшие",
        "message.supplementaries.altimeter": "Y: %d",
        "message.supplementaries.cartographers_quill": "Неизвестно",
        "message.supplementaries.compass": "X: %d, Z: %d",
        "message.supplementaries.death_marker": "Место последней смерти",
        "message.supplementaries.quill_failed": "Перо картографа не смогло завершить поиск.",
        "message.supplementaries.quill_finished": "Карта картографа готова.",
        "message.supplementaries.quiver.tooltip": "%s [%s]",
        "message.supplementaries.safe.assigned_key_generic": "Назначено ключу",
        "message.supplementaries.tattered": "Потрёпанная",
        "painting.supplementaries.bombs.author": "Plantkillable",
        "painting.supplementaries.bombs.title": "Бомбы",
        "supplementaries.virtual_resourcepack.description": "Динамические ресурсы времени выполнения",
        "trinkets.slot.chest.quiver": "Колчан",
        "wood_type.domum_ornamentum.cactus": "зелёного кактуса",
        "wood_type.domum_ornamentum.cactus_extra": "кактуса",
        "wood_type.twilightforest.dark": "тёмного дерева",
        "wood_type.twilightforest.sorting": "сортировочного дерева",
        "wood_type.twilightforest.time": "дерева времени",
        "wood_type.twilightforest.trans": "дерева трансформации",
    },
    "itemfilters": {
        "itemfilters.help_text.damage": "Повреждение предмета\n▶ Можно использовать операторы сравнения, например \"<10\" или \">=5\",\nа также проценты, например \">50%\"",
        "itemfilters.help_text.filter": "Фильтр (ПКМ, чтобы очистить)",
        "itemfilters.help_text.max_count": "Максимальный размер стака\n▶ Можно использовать операторы сравнения, например \"<64\" или \">=16\"",
        "itemfilters.help_text.nbt": "Строка NBT\n▶ Например: { text:\"hello\", value: 1, active: true }",
        "itemfilters.help_text.regex": "Регулярное выражение\nСопоставляется с идентификатором предмета\n▶ Например, \"^minecraft:\" соответствует всем предметам Minecraft",
        "itemfilters.help_text.variants": "Tab, колёсико мыши или ↑/↓: переместить выделение\nEnter: выбрать выделенное",
        "itemfilters.help_text.weak_nbt": "Неполная строка NBT\n▶ Например: { text:\"hello\", value: 1, active: true }\n▶ Проверяются только указанные поля NBT; остальные поля предмета игнорируются",
        "itemfilters.variants": "Варианты [%d]",
    },
    "immersiveengineering": {
        "advancement.immersiveengineering.buy_oremap": "Крестик отмечает место",
        "advancement.immersiveengineering.buy_oremap.desc": "Купите карту месторождения у инженера-строителя",
        "advancement.immersiveengineering.buy_shaderbag": "Модный шопинг",
        "advancement.immersiveengineering.buy_shaderbag.desc": "Купите мешок шейдеров у стилиста",
        "advancement.immersiveengineering.chorus_cloche": "Инопланетная теплица",
        "advancement.immersiveengineering.chorus_cloche.desc": "Вырастите плод хоруса в садовом клоше",
        "advancement.immersiveengineering.chute_bonk": "Неудобный короткий путь",
        "advancement.immersiveengineering.chute_bonk.desc": "Прокатитесь по желобам из листового металла",
        "advancement.immersiveengineering.craft_batcher": "Придержи-ка",
        "advancement.immersiveengineering.craft_batcher.desc": "Создайте дозатор предметов",
        "advancement.immersiveengineering.craft_drop_conveyor": "Спускаемся",
        "advancement.immersiveengineering.craft_drop_conveyor.desc": "Создайте сбрасывающую конвейерную ленту",
        "advancement.immersiveengineering.craft_duroplast": "Современные материалы",
        "advancement.immersiveengineering.craft_duroplast.desc": "Создайте лист дюропласта",
        "advancement.immersiveengineering.craft_extract_conveyor": "На выход",
        "advancement.immersiveengineering.craft_extract_conveyor.desc": "Создайте извлекающую конвейерную ленту",
        "advancement.immersiveengineering.craft_powerpack": "Портативный источник частиц",
        "advancement.immersiveengineering.craft_powerpack.desc": "Создайте конденсаторный рюкзак",
        "advancement.immersiveengineering.craft_router": "Цветовая маркировка!",
        "advancement.immersiveengineering.craft_router.desc": "Создайте сортировщик предметов",
        "advancement.immersiveengineering.craft_sheetmetal": "Красиво и прочно",
        "advancement.immersiveengineering.craft_sheetmetal.desc": "Создайте листовой металл",
        "advancement.immersiveengineering.craft_treatedwood": "Пропитано и готово",
        "advancement.immersiveengineering.craft_treatedwood.desc": "Создайте обработанную древесину",
        "advancement.immersiveengineering.creosote": "Только не пейте…",
        "advancement.immersiveengineering.creosote.desc": "Наберите ведро креозота",
        "advancement.immersiveengineering.kill_illager": "Превосходящее вооружение",
        "advancement.immersiveengineering.kill_illager.desc": "Убейте разбойника из револьвера, рельсотрона или химического распылителя. Остерегайтесь новых налётчиков!",
        "advancement.immersiveengineering.liquid_concrete": "Вот что бывает со стукачами…",
        "advancement.immersiveengineering.liquid_concrete.desc": "Увязните ногами в бетоне",
        "advancement.immersiveengineering.main_root.desc": "Читайте руководство!",
        "advancement.immersiveengineering.mb_cokeoven": "Концентрированный углерод",
        "advancement.immersiveengineering.mb_cokeoven.desc": "Соберите многоблочную коксовую печь",
        "advancement.immersiveengineering.mb_fermenter": "Самогон!",
        "advancement.immersiveengineering.mb_fermenter.desc": "Соберите многоблочный бродильный аппарат",
        "advancement.immersiveengineering.mb_mixer": "Промышленное зельеварение",
        "advancement.immersiveengineering.mb_mixer.desc": "Соберите многоблочный смеситель",
        "advancement.immersiveengineering.mb_refinery": "Химическая переработка",
        "advancement.immersiveengineering.mb_refinery.desc": "Соберите многоблочный нефтеперерабатывающий завод",
        "advancement.immersiveengineering.mb_squeezer": "А ореховое молоко получится?",
        "advancement.immersiveengineering.mb_squeezer.desc": "Соберите многоблочный выжиматель",
        "advancement.immersiveengineering.mb_tank": "Водонапорная башня",
        "advancement.immersiveengineering.mb_tank.desc": "Соберите многоблочный резервуар",
        "advancement.immersiveengineering.multiblocks_root": "Многоблочные конструкции",
        "advancement.immersiveengineering.multiblocks_root.desc": "Большие машины для больших заводов",
        "advancement.immersiveengineering.place_dynamo": "Двигатель наоборот",
        "advancement.immersiveengineering.place_dynamo.desc": "Установите кинетический генератор",
        "advancement.immersiveengineering.secret_bttf": "1,21 гигаватта!",
        "advancement.immersiveengineering.secret_bttf.desc": "Когда эта крошка разгонится до 88 миль в час, ты увидишь такое…",
        "advancement.immersiveengineering.secret_friedbird": "Жареная птица",
        "advancement.immersiveengineering.secret_friedbird.desc": "Изоляции не оказалось",
        "advancement.immersiveengineering.skyhook_distance": "Букер, лови!",
        "advancement.immersiveengineering.skyhook_distance.desc": "Преодолейте на небесном крюке в сумме 1 км",
        "advancement.immersiveengineering.tools_root": "Инструменты и улучшения",
        "advancement.immersiveengineering.tools_root.desc": "Верстак инженера позволяет улучшать инструменты",
        "advancement.immersiveengineering.upgrade_powerpack": "Особый набор Спенглера и Стэнца",
        "advancement.immersiveengineering.upgrade_powerpack.desc": "Установите на конденсаторный рюкзак максимум улучшений",
        "advancement.immersiveengineering.villager": "Коллеги-инженеры",
        "advancement.immersiveengineering.villager.desc": "Познакомьтесь с жителем-инженером",
        "chat.immersiveengineering.info.bottling_machine.completeFill": "Удерживать ёмкости до полного наполнения",
        "chat.immersiveengineering.info.bottling_machine.partialFill": "Разрешить частичное наполнение",
        "chat.immersiveengineering.info.drill_mode.multi": "Добывать несколько блоков",
        "chat.immersiveengineering.info.drill_mode.single": "Добывать один блок",
        "chat.immersiveengineering.info.glider.too_fast": "Скорость слишком велика — планер получит повреждения",
        "chat.immersiveengineering.info.redstoneLevel": "Уровень сигнала редстоуна: %1$s",
        "config.jade.plugin_immersiveengineering.hemp": "Рост промышленной конопли",
        "config.jade.plugin_immersiveengineering.multiblock_icon": "Значки многоблочных конструкций",
        "desc.immersiveengineering.flavour.toolupgrade_drill_fortune": "Увеличивает количество добычи из руд",
        "desc.immersiveengineering.flavour.toolupgrade_powerpack_antenna": "Заряжает конденсаторный рюкзак от проводов",
        "desc.immersiveengineering.flavour.toolupgrade_powerpack_induction": "Заряжает весь инвентарь",
        "desc.immersiveengineering.flavour.toolupgrade_powerpack_tesla": "Бьёт током нападающих",
        "desc.immersiveengineering.info.mineral.amethyst_crevasse": "Аметистовая расселина",
        "desc.immersiveengineering.info.mineral.ancient_seabed": "Древнее морское дно",
        "desc.immersiveengineering.info.mineral.cooled_lava_tube": "Остывший лавовый тоннель",
        "desc.immersiveengineering.info.mineral.hardened_clay_pan": "Пласт затвердевшей глины",
        "desc.immersiveengineering.info.mineral.nether_silt": "Песок душ",
        "desc.immersiveengineering.info.noChargeOnArmor": "Нельзя заряжать, пока прикреплено к броне",
        "desc.immersiveengineering.info.operator.imply": "ИМПЛИКАЦИЯ",
        "desc.immersiveengineering.info.operator.nimply": "НЕИМПЛИКАЦИЯ",
        "desc.immersiveengineering.info.redstoneLevel": "Уровень сигнала редстоуна: %1$s",
        "desc.immersiveengineering.info.shader.details.acepride": "Лучше просто обнимитесь!",
        "desc.immersiveengineering.info.shader.details.bipride": "Это не просто этап.",
        "desc.immersiveengineering.info.shader.details.enbypride": "Гендер не бинарен!",
        "desc.immersiveengineering.info.shader.details.gaypride": "Даже пингвины так делают!",
        "desc.immersiveengineering.info.shader.details.lesbianpride": "Археологи назовут их соседками.",
        "desc.immersiveengineering.info.shader.details.transpride": "Защитим транс-детей! Права транс-людей — права человека, сейчас и навсегда!",
        "entity.immersiveengineering.bulwark": "Защитник",
        "entity.immersiveengineering.chemthrower_shot": "Капля химического распылителя",
        "entity.immersiveengineering.commando": "Коммандос",
        "entity.immersiveengineering.fusilier": "Фузилёр",
        "entity.immersiveengineering.railgun_shot": "Стержень рельсотрона",
        "entity.immersiveengineering.revolver_shot": "Пуля",
        "entity.immersiveengineering.revolver_shot_flare": "Сигнальная ракета",
        "entity.immersiveengineering.revolver_shot_homing": "Самонаводящаяся пуля",
        "entity.immersiveengineering.revolver_shot_wolfpack": "Снаряд «Волчья стая»",
        "fluid_type.immersiveengineering.acetaldehyde": "Ацетальдегид",
        "fluid_type.immersiveengineering.herbicide": "Гербицид",
        "fluid_type.immersiveengineering.phenolic_resin": "Фенольная смола",
        "fluid_type.immersiveengineering.potion": "Зелье",
        "fluid_type.immersiveengineering.redstone_acid": "Редстоуновая кислота",
        "gui.immersiveengineering.config.output_threshold": "Порог сигнала: ",
        "immersiveengineering.optifinePoseStackWarning": "Immersive Engineering обнаружил несовместимую версию OptiFine. Из-за способа внесения изменений эта версия OptiFine удаляет добавленные Forge методы, которые прямо или косвенно используют Immersive Engineering и многие другие моды. В результате игра может вылетать в самых неожиданных ситуациях — например, когда поиск находит определённые предметы. Не используйте OptiFine, пока проблема не будет исправлена.",
        "manual.immersiveengineering.early_machines": "Верстаки и печи",
        "material.treatedwood.name": "Обработанная древесина",
        "subtitle.immersiveengineering.assembler": "Сборщик ритмично работает",
        "subtitle.immersiveengineering.bottling": "Разливочная машина наполняет ёмкость",
        "subtitle.immersiveengineering.fermenter": "Бродильный аппарат гудит",
        "subtitle.immersiveengineering.glider": "Планер получает повреждения",
        "subtitle.immersiveengineering.mixer": "Смеситель перемешивает и скребёт",
        "subtitle.immersiveengineering.preheater": "Воздухонагреватель с шумом выпускает воздух",
        "subtitle.immersiveengineering.refinery": "Нефтеперерабатывающий завод гудит",
        "subtitle.immersiveengineering.saw_empty": "Лесопилка визжит без древесины",
        "subtitle.immersiveengineering.saw_full": "Лесопилка визжит, распиливая древесину",
        "subtitle.immersiveengineering.saw_shutdown": "Диск лесопилки останавливается",
        "subtitle.immersiveengineering.saw_startup": "Диск лесопилки раскручивается",
    },
    "ftbquests": {
        "commands.ftbquests.command.error.invalid_id": "Недопустимый ID объекта: %s!",
        "commands.ftbquests.command.error.invalid_type": "Недопустимый тип changeProgress: %s!",
        "commands.ftbquests.command.error.no_file": "Файл квестов не найден. Что происходит?!",
        "commands.ftbquests.command.error.no_inventory": "В целевом блоке нет инвентаря!",
        "commands.ftbquests.command.error.no_object": "Объект квеста с ID %s не найден!",
        "commands.ftbquests.command.error.not_editing": "Для этого включите режим редактирования: /ftbquests editing_mode",
        "commands.ftbquests.command.feedback.reloaded": "Данные квестов перезагружены из файла!",
        "commands.ftbquests.command.feedback.reloaded.disclaimer": "Примечание: перезагрузка квестов предназначена для разработчиков и не рекомендуется на работающих серверах.",
        "commands.ftbquests.command.feedback.rewards_blocked": "Блокировка наград за квесты для команды «%s»: %s",
        "commands.ftbquests.command.feedback.table_exported": "Таблица наград «%s» успешно экспортирована в целевой блок; предметов: %s!",
        "commands.ftbquests.command.feedback.table_imported": "Таблица наград «%s» успешно импортирована; предметов: %s!",
        "commands.ftbquests.command.feedback.table_too_many_items": "ВНИМАНИЕ: в таблице %s больше предметов, чем вмещает целевой блок. Экспорт остановлен!",
        "commands.ftbquests.locked.disabled": "Квесты для %s разблокированы",
        "commands.ftbquests.locked.enabled": "Квесты для %s заблокированы",
        "ftbquests.chapter.default_hide_dependency_lines": "По умолчанию скрывать линии зависимостей",
        "ftbquests.chapter.default_min_width": "Минимальная ширина открытого окна квеста по умолчанию",
        "ftbquests.chapter.hide_quest_details_until_startable": "Скрывать сведения о квесте до его доступности",
        "ftbquests.chapter.hide_quest_until_deps_visible": "Скрывать квесты, пока не видны зависимости",
        "ftbquests.chapter.image.alpha": "Прозрачность изображения",
        "ftbquests.chapter.image.click.tooltip": "Действие при нажатии на изображение:\n• открыть страницу или файл по URL http://, https:// или file:///;\n• выполнить команду через 'command:<команда>';\n• перейти к квесту через '#<id_квеста>' (ID можно получить кнопкой «Копировать ID»);\n• вызвать CustomClickEvent для KubeJS или другого мода через 'custom:<идентификатор_ресурса>'.",
        "ftbquests.chapter.image.color": "Оттенок изображения",
        "ftbquests.chapter.image.corner": "Повернуть и сместить от угла",
        "ftbquests.chapter.image.order": "Порядок изображения",
        "ftbquests.chapter.image.order.tooltip": "Порядок отрисовки изображений в одной главе.\nИзображения с большим значением отображаются поверх изображений с меньшим.",
        "ftbquests.chapter.progression_mode": "Режим прохождения",
        "ftbquests.chapter_group": "Группа глав",
        "ftbquests.chapter_groups": "Группы глав",
        "ftbquests.file.detection_delay": "Минимальный интервал автообнаружения предметов",
        "ftbquests.file.detection_delay.tooltip": "Минимальный интервал в тиках между проверками изменившегося инвентаря игрока.\nБольшие значения снижают нагрузку на сервер, особенно при частых изменениях инвентаря, но задерживают сообщения об автоматическом выполнении квестов.",
        "ftbquests.file.lock_message": "Сообщение о блокировке",
        "ftbquests.file.progression_mode": "Режим прохождения",
        "ftbquests.file.progression_mode.flexible": "Гибкий",
        "ftbquests.file.progression_mode.linear": "Линейный",
        "ftbquests.file.progression_mode.tooltip": "Линейный: квест нужно завершить до начала зависимых квестов.\nГибкий: задания в зависимых квестах можно выполнять когда угодно,\nно завершить их можно лишь после выполнения зависимости.",
        "ftbquests.gui.bulk_change_size": "Изменить размер у всех…",
        "ftbquests.gui.change_group": "Изменить группу",
        "ftbquests.gui.clear_formatting": "Очистить форматирование",
        "ftbquests.gui.clear_reward_all": "Удалить награды у всех",
        "ftbquests.gui.copy_id.paste_hint": "Этот ID можно использовать для вставки квестов или ссылок на них",
        "ftbquests.gui.copy_id.quick_properties": "Быстро изменить свойства…",
        "ftbquests.gui.edit": "Изменить",
        "ftbquests.gui.edit_description": "Редактор описания квеста",
        "ftbquests.gui.edit_description.help": "Shift+Enter: сохранить и выйти",
        "ftbquests.gui.edit_linked_quest": "Изменить связанный квест",
        "ftbquests.gui.fix_aspect_ratio_h": "Подогнать высоту под соотношение сторон",
        "ftbquests.gui.fix_aspect_ratio_w": "Подогнать ширину под соотношение сторон",
        "ftbquests.gui.goto_linked_quest": "Перейти к связанному квесту (глава: %s)",
        "ftbquests.gui.image": "Добавить изображение",
        "ftbquests.gui.line": "Добавить строку текста",
        "ftbquests.gui.linked_quest_id": "ID связанного квеста: %s",
        "ftbquests.gui.page_break": "Добавить разрыв страницы",
        "ftbquests.gui.paste": "Вставить квест",
        "ftbquests.gui.paste_image": "Вставить изображение",
        "ftbquests.gui.paste_link": "Вставить ссылку на квест",
        "ftbquests.gui.paste_no_deps": "Вставить квест без зависимостей",
        "ftbquests.gui.paste_task": "Вставить задание",
        "ftbquests.gui.save_on_server": "Сохранить на сервере сейчас",
        "ftbquests.gui.saved_on_server": "Квесты сохранены на сервере",
        "ftbquests.gui.select_reward_table": "Выбрать таблицу наград",
        "ftbquests.gui.undo": "Отменить",
        "ftbquests.gui.use_as_quest_icon": "Использовать значок задания для квеста",
        "ftbquests.gui.view_quest_links": "Показать ссылки на квест",
        "ftbquests.message.configurator_bound": "Настройщик привязан: %s",
        "ftbquests.message.missing_task_screen": "Экран задания отсутствует!",
        "ftbquests.message.task_screen_inaccessible": "Отсюда нет доступа к экрану задания!",
        "ftbquests.objects": "Объектов: %d",
        "ftbquests.quest.hidden_quests_footer": "Скрыто: %d",
        "ftbquests.quest.hide_dependency_lines.tooltip": "Управляет отображением линий от квестов, открывающих этот квест",
        "ftbquests.quest.hide_dependent_lines": "Скрыть линии зависимых квестов",
        "ftbquests.quest.hide_dependent_lines.tooltip": "Управляет отображением линий к квестам, которые открывает этот квест",
        "ftbquests.quest.hide_details_until_startable": "Скрывать сведения до доступности",
        "ftbquests.quest.hide_details_until_startable.tooltip": "Если включено, текст и задания квеста нельзя просмотреть, пока квест недоступен для начала",
        "ftbquests.quest.ignore_reward_blocking": "Игнорировать блокировку наград",
        "ftbquests.quest.ignore_reward_blocking.tooltip": "Выдавать награды квеста, даже если команда заблокировала их командой '/ftbquests block_rewards'",
        "ftbquests.quest.invisible": "Невидимый",
        "ftbquests.quest.invisible.tooltip": "Квест невидим игрокам до завершения",
        "ftbquests.quest.invisible_until_tasks": "Невидим до выполнения X заданий",
        "ftbquests.quest.invisible_until_tasks.tooltip": "Действует, только если включена невидимость.\nПри значении больше 0 квест станет видимым после выполнения X или более заданий.",
        "ftbquests.quest.locked": "Заблокирован: есть невыполненные зависимости",
        "ftbquests.quest.min_required_header": "Требуется: %d",
        "ftbquests.quest.progression_mode": "Режим прохождения",
        "ftbquests.quest_link": "Ссылка на квест",
        "ftbquests.reward.blocked": "Заблокировано наград: %d; команда «%s»",
        "ftbquests.reward.exclude_from_claim_all": "Не учитывать при получении всех наград",
        "ftbquests.reward.exclude_from_claim_all.tooltip": "Игнорировать эту награду при нажатии «Получить все награды».\nПараметр нельзя изменить для наград типов «Добыча», «Случайная» и «Выбор».",
        "ftbquests.reward.this_blocked": "Награда заблокирована для команды «%s»",
        "ftbquests.reward_table.loot_crate.item_name.tooltip": "Можно указать ключ перевода",
        "ftbquests.task.ftbquests.item.match_nbt": "Сопоставлять NBT",
        "ftbquests.task.ftbquests.item.match_nbt.tooltip": "По умолчанию: предмет должен входить в тег 'itemfilters:check_nbt'.\nНет: никогда не проверять NBT.\nДа: всегда проверять NBT.",
        "ftbquests.task.ftbquests.item.task_screen_only": "Только через экран задания",
        "ftbquests.task.ftbquests.item.task_screen_only.tooltip": "Если включено, предметы можно передавать только по трубе в экран задания.\nДействует лишь при включённом расходовании предметов в этом задании.",
        "ftbquests.task.ftbquests.item.weak_nbt_match": "Неполное сопоставление NBT",
        "ftbquests.task.ftbquests.item.weak_nbt_match.tooltip": "Нет: требуется точное совпадение NBT.\nДа: дополнительные поля NBT проверяемого предмета не мешают совпадению.",
        "ftbquests.task.ftbquests.location.x.tooltip": "Минимальная X игрока: X игрока должна быть >= X и < X+W",
        "ftbquests.task.ftbquests.location.y.tooltip": "Минимальная Y игрока: Y игрока должна быть >= Y и < Y+H",
        "ftbquests.task.ftbquests.location.z.tooltip": "Минимальная Z игрока: Z игрока должна быть >= Z и < Z+D",
        "ftbquests.task.ftbquests.observation.to_observe": "Наблюдать",
        "ftbquests.task.ftbquests.structure": "Найти структуру",
        "ftbquests.task.ftbquests.structure.structure": "Структура",
        "ftbquests.task.ftbquests.tech_reborn_energy": "Энергия Tech Reborn",
        "ftbquests.task.ftbquests.tech_reborn_energy.text": "%d E",
        "ftbquests.task.ftbquests.tech_reborn_energy.value": "E",
        "ftbquests.task.task_screen_only": "Предметы можно передавать ТОЛЬКО через экран задания!",
        "ftbquests.task_title": "Название задания",
        "ftbquests.ui.old_scroll_wheel": "Старое поведение колёсика мыши",
        "ftbquests.ui.old_scroll_wheel.tooltip": "Если выключено, колёсико прокручивает вверх и вниз; Shift перемещает вид, Ctrl меняет масштаб.\nЕсли включено, колёсико только меняет масштаб, как в версии 1.19 и старше.",
    },
    "bdlib": {
        "bdlib.config.power.activation": "Энергия активации",
        "bdlib.config.power.capacity": "Ёмкость энергии",
        "bdlib.config.power.maxinput": "Максимальный ввод энергии",
        "bdlib.dumpregistry.error": "Не удалось сохранить реестры: %s",
        "bdlib.dumpregistry.saved": "Реестры сохранены в %s",
        "bdlib.format.amount.unit": "%s %s",
        "bdlib.format.cap": "%s/%s",
        "bdlib.format.cap.unit": "%s/%s %s",
        "bdlib.format.rate": "%s/т",
        "bdlib.format.rate.unit": "%s %s/т",
        "bdlib.label.empty": "Пусто",
        "bdlib.multiblock.disabled": "Отключено",
        "bdlib.multiblock.face.down": "Снизу",
        "bdlib.multiblock.face.east": "Восток",
        "bdlib.multiblock.face.north": "Север",
        "bdlib.multiblock.face.south": "Юг",
        "bdlib.multiblock.face.up": "Сверху",
        "bdlib.multiblock.face.west": "Запад",
        "bdlib.multiblock.incomplete": "Машина не собрана; требуется как минимум:",
        "bdlib.multiblock.incomplete.entry": "- %s %s",
        "bdlib.multiblock.notconnected": "Не подключено к рабочей машине",
        "bdlib.multiblock.tip.controller": "Возможные модули:",
        "bdlib.multiblock.tip.module": "Можно установить в:",
        "bdlib.multiblock.tip.module.max": "* %s (не более %s)",
        "bdlib.multiblock.tip.module.range": "* %s (%s–%s)",
        "bdlib.multiblock.tip.output.pos": "%s, %s, %s — %s",
        "bdlib.multiblock.toomanyoutputs": "Подключено слишком много выходов; новое соединение невозможно",
        "bdlib.oredistribution.entry": "%s %s — %s (%s%%)",
        "bdlib.oredistribution.error": "Не удалось сохранить отчёт о распределении руд: %s",
        "bdlib.oredistribution.saved": "Отчёт о распределении руд сохранён в %s",
        "bdlib.oredistribution.start1": "Проверяется распределение руд от (%s,%s,%s) до (%s,%s,%s), измерение %s",
        "bdlib.oredistribution.start2": "Сервер может некоторое время тормозить",
        "bdlib.oredistribution.usage": "Использование: /oredistribution <радиус> [<мин. высота>] [<макс. высота>] [--file]",
        "bdlib.oredistribution.warn": "%s Внимание: у %s создано несколько вариантов:",
        "bdlib.rsmode.always": "Всегда включено",
        "bdlib.rsmode.never": "Отключено",
        "bdlib.rsmode.rs_off": "Выключать сигналом редстоуна",
        "bdlib.rsmode.rs_on": "Включать сигналом редстоуна",
        "bdlib.unit.fe": "FE",
        "bdlib.unit.mb": "мБ",
    },
    "nochatreports": {
        "algorithm.nochatreports.aes_cfb8_base64": "§lAES/CFB8+Base64R§r\nСтандартный алгоритм симметричного шифрования. Использует 128-битные ключи, а результат кодирует особой разновидностью Base64 для передачи через чат Minecraft. Недостаток: сообщения становятся примерно на 30% длиннее, и сервер может обрезать их при превышении лимита.",
        "algorithm.nochatreports.aes_cfb8_base64.name": "AES/CFB8+Base64R",
        "algorithm.nochatreports.aes_ecb_base64": "§lAES/ECB+Base64R§r\nЗаметно менее безопасен, чем режим CFB, зато экономит несколько байтов, поскольку не требует вектора инициализации. Но всё же лучше шифра Цезаря.",
        "algorithm.nochatreports.aes_ecb_base64.name": "AES/ECB+Base64R",
        "algorithm.nochatreports.aes_gcm_base64": "§lAES/GCM+Base64R§r\nПовышенная безопасность ценой сильного увеличения сообщения: 12 байтов на вектор инициализации, 12 на тег аутентификации и сверху кодирование Base64. Выбирайте, если безопасность важнее всего.",
        "algorithm.nochatreports.aes_gcm_base64.name": "AES/GCM+Base64R",
        "algorithm.nochatreports.caesar": "§lШифр Цезаря§r\nШуточный шифр. Вы просто надеетесь, что люди сдадутся, даже не пытаясь расшифровать сообщения. Иногда так и бывает, поэтому пригодность зависит от вашей модели угроз.\nКлюч должен быть целым числом от 1 до 1024. Сдвиг выполняется по коду символа, а не по алфавиту, чтобы работал любой язык.",
        "algorithm.nochatreports.caesar.name": "Шифр Цезаря",
        "gui.NoChatReports.showEncryptionButtonWarning": "§cПараметр ниже не отключает шифрование, а лишь скрывает кнопку!",
        "gui.nochatreports.encryption_config.algorithm": "Алгоритм: %1$s",
        "gui.nochatreports.encryption_config.default_key": "<по умолчанию: %1$s>",
        "gui.nochatreports.encryption_config.dice_tooltip": "Создать новый случайный ключ для выбранного алгоритма шифрования.",
        "gui.nochatreports.encryption_config.encrypt_public": "Шифровать публичные сообщения",
        "gui.nochatreports.encryption_config.header": "Настройки шифрования",
        "gui.nochatreports.encryption_config.key_desc": "§lКлюч шифрования§r\nКлюч для шифрования и расшифровки ваших сообщений. Формат зависит от алгоритма; для AES это 128 бит двоичных данных в Base64.",
        "gui.nochatreports.encryption_config.pass_not_allowed": "<не поддерживается>",
        "gui.nochatreports.encryption_config.passphrase_desc": "§lПарольная фраза§r\nВместо случайного ключа его можно получить из выбранной парольной фразы. Используйте надёжную фразу. Парольные фразы поддерживают не все алгоритмы.",
        "gui.nochatreports.encryption_config.validation_failed": "Проверка ключа: §c§lне пройдена",
        "gui.nochatreports.encryption_config.validation_ok": "Проверка ключа: §a§lпройдена",
        "gui.nochatreports.encryption_tooltip": "§lШифрование:§r %1$s\nПКМ — настроить.\n\nКогда шифрование включено, удерживайте §n§lCtrl§r при отправке, чтобы не применять его к сообщению.",
        "gui.nochatreports.encryption_tooltip_invalid": "§lШифрование:§r %1$s\n§cНастройка недействительна. Нажмите, чтобы исправить.",
        "gui.nochatreports.encryption_warning.contents": "Сообщения можно шифровать секретным ключом. Расшифровать их смогут только те, кто знает ключ. No Chat Reports автоматически расшифровывает все зашифрованные сообщения, если функция включена и указан подходящий ключ.\nОднако шифрование — не волшебная палочка. Модераторы сторонних серверов могут заглушить или заблокировать вас за отправку непонятного набора символов. Рекомендуется создать собственный ключ и передавать его другим только по защищённым каналам. Нажмите «Подробнее», чтобы узнать, когда и как следует применять шифрование.",
        "gui.nochatreports.encryption_warning.header": "О шифровании",
        "gui.nochatreports.status_realms": "Это сервер Realms. Здесь невозможно предотвратить жалобы на чат, а Mojang также автоматически отслеживает чат для выявления потенциального вреда в сети и передачи сообщений на проверку человеку — независимо от желания владельца мира. Единственная надежда — шифрование чата.",
        "gui.nochatreports.status_unknown": "No Chat Reports был переключён во время сеанса. Оценить безопасность сервера можно только при входе. Переподключитесь к серверу.",
        "option.NoChatReports.postDisconnectAwaitSeconds": "Ожидание после отключения, с",
        "option.NoChatReports.postDisconnectAwaitSeconds.tooltip": "Похоже на §oreconnectAwaitSeconds§r, но отсчёт начинается сразу после обычного отключения игрока от сервера. Если при повторном входе эта задержка больше §oreconnectAwaitSeconds§r, применяется она.",
        "option.NoChatReports.reconnectAwaitSeconds": "Ожидание переподключения, с",
        "option.NoChatReports.reconnectAwaitSeconds.tooltip": "Сколько секунд клиент ждёт до автоматического переподключения, если сервер отклонил вход без ключа подписи чата, а пользователь согласился войти на небезопасный сервер.",
        "option.NoChatReports.serverSigningChecks": "Проверки подписи серверов",
        "option.NoChatReports.serverSigningChecks.tooltip": "Список разрешённых серверов и время последней проверки обязательной подписи в секундах эпохи. Обычно вручную изменять его не нужно.",
        "option.NoChatReports.showEncryptionButton": "Показывать кнопку шифрования",
        "option.NoChatReports.showEncryptionButton.tooltip": "Если выключить, кнопка шифрования исчезнет с экрана чата. Само шифрование при этом автоматически не отключается.",
        "option.NoChatReports.signingCheckDelaySeconds": "Интервал проверки подписи, с",
        "option.NoChatReports.signingCheckDelaySeconds.tooltip": "Интервал в секундах между проверками того, требуют ли серверы из списка подпись чата. Значение 0 выполняет проверку при каждом входе, как для серверов не из списка.",
        "tag.nochatreports.encrypted": "Зашифровано с помощью: %1$s",
        "tag.nochatreports.encrypted_original": "Не расшифровано: %1$s",
    },
    "blockcarpentry": {
        "advancements.blockcarpentry.pane.description": "Эти панели — настоящая боль в стекле!",
        "advancements.blockcarpentry.pane.title": "Без паники, это панель!",
        "advancements.blockcarpentry.sign.description": "Это знак свыше!",
        "advancements.blockcarpentry.sign.title": "Распишитесь здесь!",
        "message.blockcarpentry.can_entity_destroy": "Существа больше не могут разрушить этот блок!",
        "message.blockcarpentry.can_entity_destroy_already": "Этот блок уже защищён от разрушения существами!",
        "message.blockcarpentry.chisel.enlarge": "Увеличивать",
        "message.blockcarpentry.chisel.mode": "Режим стамески при нажатии ПКМ по полным блокам: %s",
        "message.blockcarpentry.chisel.shrink": "Уменьшать",
        "message.blockcarpentry.discord1": "§6[BlockCarpentry]§r Заходите на наш §3сервер Discord§r. Если вы",
        "message.blockcarpentry.discord2": "не понимаете, как работает какая-либо функция, там можно попросить помощи.",
        "message.blockcarpentry.discord3": "Там же можно поделиться своими предложениями!",
        "message.blockcarpentry.discord_disable1": "§6[BlockCarpentry]§r Это сообщение можно отключить в",
        "message.blockcarpentry.discord_disable2": "§3файле конфигурации BlockCarpentry§r.",
        "message.blockcarpentry.enchanting_power": "Теперь этот блок усиливает стол зачарований!",
        "message.blockcarpentry.exception": "В блоке произошла ошибка. Если сообщение появляется снова, проверьте журнал игры.",
        "message.blockcarpentry.friction": "Трение блока: %s",
        "message.blockcarpentry.paintbrush.custom": "Задана грань произвольной формы",
        "message.blockcarpentry.paintbrush.fixed": "Координаты UV текстуры зафиксированы",
        "message.blockcarpentry.paintbrush.rectangle": "Задана прямоугольная грань",
        "message.blockcarpentry.paintbrush.relaxed": "Координаты UV текстуры освобождены",
        "message.blockcarpentry.rotation.axis": "Вращение вокруг оси %s",
        "message.blockcarpentry.rotation.face": "Грань блока повёрнута по часовой стрелке",
        "message.blockcarpentry.strength": "Устойчивость блока к взрывам: %s",
        "message.blockcarpentry.strength_max": "Устойчивость блока к взрывам улучшена до максимума: %s",
        "message.blockcarpentry.sustainability": "Теперь на этом блоке могут расти растения!",
        "tooltip.blockcarpentry.debug_item": "§6§oКрадитесь и нажмите ПКМ по блоку, чтобы показать его данные NBT.",
    },
    "tombstone": {
        "stat.tombstone.imbued_arrow": "Насыщенные стрелы",
        "tombstone.advancement.easter.desc": "Особые достижения во время Пасхи",
        "tombstone.advancement.easter.title": "Пасха",
        "tombstone.advancement.eat_easter_egg_food.desc": "Вы съели блюдо из теневого яйца",
        "tombstone.advancement.eat_easter_egg_food.title": "Пасхальное блюдо",
        "tombstone.advancement.expert_searcher.desc": "Вы нашли все виды пасхальных яиц",
        "tombstone.advancement.expert_searcher.title": "Искатель-эксперт",
        "tombstone.advancement.find_easter_egg.desc": "Вы нашли пасхальное яйцо",
        "tombstone.advancement.find_easter_egg.title": "Охотник за пасхальными яйцами",
        "tombstone.advancement.trade_easter_mask.desc": "Вы обменяли пасхальные яйца на маску",
        "tombstone.advancement.trade_easter_mask.title": "Как кролик",
        "tombstone.compendium.easter_egg.desc": "Ингредиент для готовки во время Пасхи.\nЕго также можно обменять у хранителя могилы.",
        "tombstone.config.easter_egg_spawn_rarity": "Редкость появления пасхальных яиц",
        "tombstone.config.easter_egg_spawn_rarity.tooltip": "Редкость появления пасхальных яиц во время Пасхи",
        "tombstone.config.level_max_shadow_walker.tooltip": "Максимальный уровень способности «Теневой бродяга»",
        "tombstone.item.easter_egg": "Пасхальное яйцо",
        "tombstone.item.easter_egg.desc": "Ингредиент для готовки",
        "tombstone.item.easter_egg_food": "Теневое яйцо под соусом бешамель",
        "tombstone.item.easter_egg_food.desc": "Вкусное блюдо с соусом бешамель",
        "tombstone.item.rabbit_mask": "Маска кролика",
        "tombstone.item.rabbit_mask.desc": "Декоративная пасхальная маска",
        "tombstone.perk.shadow_walker.disabled": "Параметр level_max_shadow_walker равен 0",
    },
    "essence": {
        "blockentity.essence.essence_station.name": "Станция эссенции",
        "blockentity.essence.resource_duplicator.name": "Дубликатор ресурсов",
        "death.attack.shocked": "%1$s слишком долго пытался плавать в грозовой воде!",
        "fluid_type.essence.lightning_water_fluid": "Грозовая вода",
        "itemGroup.essence": "Эссенция",
        "jei.essence.activated_spawner_shard": "Из этих осколков можно создавать яйца призыва.",
        "jei.essence.advanced_mob_essence": "Поместите блок базовой эссенции существ в бассейн с грозовой водой и примените катализатор улучшения, чтобы получить эту эссенцию.",
        "jei.essence.advanced_ore_essence": "Поместите блок базовой эссенции руды в бассейн с грозовой водой и примените катализатор улучшения, чтобы получить эту эссенцию.",
        "jei.essence.basic_mob_essence": "Может выпасть из любого существа.",
        "jei.essence.basic_ore_essence": "Выпадает из руды эссенции.",
        "jei.essence.elite_mob_essence": "Поместите блок улучшенной эссенции существ в бассейн с грозовой водой и примените катализатор улучшения, чтобы получить эту эссенцию.",
        "jei.essence.elite_ore_essence": "Поместите блок улучшенной эссенции руды в бассейн с грозовой водой и примените катализатор улучшения, чтобы получить эту эссенцию.",
        "jei.essence.essence_converter": "Нажмите ПКМ по блоку эссенции руды, чтобы превратить его в блок эссенции существ, или наоборот.",
        "jei.essence.essence_upgrader": "Нажмите ПКМ по базовому или улучшенному блоку эссенции существ либо руды, чтобы повысить уровень: базовая → улучшенная → элитная.",
        "jei.essence.lightning_water_block": "Примените призыватель молний к затопленному громоотводу, чтобы создать грозовую воду.",
        "jei.essence.spawner_shard": "Осколки можно получить, нажав ПКМ по спавнеру извлекателем осколков.",
        "jei.essence.spawner_shard_extractor": "Нажатие ПКМ по спавнеру ломает его, высвобождает опыт и иногда создаёт осколки спавнера.",
        "tooltip.essence.lightning_summoner.tooltip": "Зажмите SHIFT, чтобы узнать больше",
        "tooltip.essence.lightning_summoner.tooltip.shift": "Нажмите ПКМ по затопленному громоотводу, чтобы создать грозовую воду",
        "tooltip.essence.spawner_shard_extractor.tooltip": "Зажмите SHIFT, чтобы узнать больше",
        "tooltip.essence.spawner_shard_extractor.tooltip.shift": "Нажмите ПКМ по спавнеру, чтобы сломать его и получить шанс на выпадение осколков",
        "world.essence.needs_lightning_water": "Все соседние блоки должны быть грозовой водой!",
    },
    "ae2wtlib": {
        "gui.ae2wtlib.Magnet": "Фильтр магнита",
        "gui.ae2wtlib.blacklist": "Чёрный список",
        "gui.ae2wtlib.copy_insert": "Копировать в фильтр помещения",
        "gui.ae2wtlib.copy_pickup": "Копировать в фильтр подбора",
        "gui.ae2wtlib.filter": " Фильтр: ",
        "gui.ae2wtlib.insert": "Помещение",
        "gui.ae2wtlib.pickup": "Подбор",
        "gui.ae2wtlib.switch": "Сменить фильтры",
        "gui.ae2wtlib.whitelist": "Белый список",
    },
    "cloth-config2": {
        "text.cloth-config.disabled_tooltip": "Отключено: требования не выполнены",
        "text.cloth-config.testing.1": "Вы разработчик мода и хотите использовать %1$s? Для начала откройте %2$s. Также можно %3$s.",
        "text.cloth-config.testing.2": "вики Cloth Config",
        "text.cloth-config.testing.3": "без особой причины открыть файл настроек Minecraft",
    },
    "craftingtweaks": {
        "key.craftingtweaks.transfer_stack": "Перенести стак в сетку крафта",
    },
    "creativecore": {
        "minecraft.material": "Материал",
    },
    "curios": {
        "argument.entity.options.curios.description": "Инвентарь Curios существа",
        "commands.curios.drop.success": "Предметы из слота %s выброшены для %s",
        "commands.curios.dropAll.success": "Предметы из всех слотов выброшены для %s",
        "commands.curios.replace.success": "Слот %s для %s заменён на %s",
    },
    "cyclopscore": {
        "general.cyclopscore.dev_world": "Мир разработчика",
        "gui.cyclopscore.down": "Вниз",
        "gui.cyclopscore.infobook": "Информационная книга",
        "gui.cyclopscore.left": "Влево",
        "gui.cyclopscore.rewards": "Награды",
        "gui.cyclopscore.right": "Вправо",
        "gui.cyclopscore.scrollbar": "Прокрутка",
        "gui.cyclopscore.search": "Поиск",
        "gui.cyclopscore.up": "Вверх",
        "infobook.cyclopscore.external": "Веб-версия",
        "infobook.cyclopscore.keybinding": "Назначение клавиши",
        "infobook.cyclopscore.keybindings": "Назначения клавиш",
    },
    "dangerousstonecutter": {
        "death.attack.cutting": "%1$s был разрезан на %2$s",
        "death.attack.cutting.player": "%1$s был разрезан на %3$s при попытке сбежать от %2$s",
        "text.autoconfig.dangerousstonecutter.option.damage": "Размер урона",
        "text.autoconfig.dangerousstonecutter.option.enableBloodParticle": "Включить частицы крови",
        "text.autoconfig.dangerousstonecutter.option.enableJudgmentDangerous": "Включить достижение «Опасное решение»",
        "text.autoconfig.dangerousstonecutter.title": "Настройки опасного камнереза",
    },
    "decorative_blocks": {
        "key.decorative_blocks.switch_item_state": "Сменить состояние предмета",
        "wiki.decorative_blocks.copy1": "§3Обычное использование вставляет, использование крадучись копирует.",
        "wiki.decorative_blocks.copy2": "§3Скопировано: %s",
        "wiki.decorative_blocks.seat": "§3Используйте крадучись в воздухе, чтобы сменить состояние.",
        "wiki.decorative_blocks.support.behavior1": "§3Перевернуть блок вверх ногами",
        "wiki.decorative_blocks.support.behavior2": "§3Переключить сторону между большой и малой",
        "wiki.decorative_blocks.support.behavior3": "§3Скрыть или показать сторону",
        "wiki.decorative_blocks.support.condition1": "§7ПКМ в воздухе крадучись:",
        "wiki.decorative_blocks.support.condition2": "§7ПКМ топором:",
        "wiki.decorative_blocks.support.condition3": "§7ПКМ топором крадучись:",
    },
    "ding": {
        "config.ding.cat.ding.load.desc": "Настройки сигнала после загрузки игры",
        "config.ding.cat.ding.load.name": "Загрузка Minecraft",
        "config.ding.cat.ding.resourcesReload.desc": "Настройки сигнала после перезагрузки ресурсов",
        "config.ding.cat.ding.resourcesReload.name": "Перезагрузка ресурсов",
        "config.ding.cat.ding.world.desc": "Настройки сигнала после загрузки мира при подключении к серверу",
        "config.ding.cat.ding.world.name": "Загрузка мира",
        "config.ding.prop.volume.desc": "Громкость сигнала после загрузки Minecraft",
        "config.ding.prop.volume.name": "Громкость при загрузке игры",
        "config.ding.prop.volumeResourcesReload.desc": "Громкость сигнала после перезагрузки ресурсов",
        "config.ding.prop.volumeResourcesReload.name": "Громкость при перезагрузке ресурсов",
        "config.ding.prop.volumeWorld.desc": "Громкость сигнала после загрузки мира при подключении к серверу",
        "config.ding.prop.volumeWorld.name": "Громкость при загрузке мира",
    },
    "extremesoundmuffler": {
        "slider.btn.volume": "Громкость: %s",
    },
    "ftblibrary": {
        "ftblibrary.empty": "Пусто",
        "ftblibrary.gui.listSize": "Предметов: %d",
        "ftblibrary.gui.listSize1": "1 предмет",
        "ftblibrary.mb": "%d мБ: %s",
        "ftblibrary.select_image.rescan": "Повторно найти изображения",
        "ftblibrary.select_image.scanning": "Поиск изображений — это может занять несколько секунд…",
        "ftblibrary.select_item.list_mode.jei": "JEI",
        "ftblibrary.select_item.list_mode.rei": "REI",
        "sidebar_group.ftblibrary.cheat": "FTB Library — читы",
        "sidebar_group.ftblibrary.info": "FTB Library — сведения",
        "sidebar_group.ftblibrary.util": "FTB Library — инструменты",
    },
    "itemphysic": {
        "item.tooltip.pickup.keybind": "Нажмите «%s», чтобы подобрать",
    },
    "jade": {
        "config.jade.danger_zone_desc": "Спокойно, это не §oDanger Zone",
        "config.jade.display_mode_lite_desc.fabric": "Удерживайте Shift, чтобы показать дополнительные сведения",
        "config.jade.format_title_name": "Название заголовка",
        "config.jade.plugin_jade.registry_name_off": "ВЫКЛ.",
        "config.jade.plugin_jade.registry_name_on": "ВКЛ.",
        "gui.jade.server_features": "*{0} {0,choice,1#серверная функция|1<серверных функций}",
        "gui.jade.server_features.tip": "На этой странице доступно {0} {0,choice,1#серверная функция|1<серверных функций}.\nУстановите Jade на сервер, чтобы полностью их включить.",
        "jade.fluid2": "%s %s / %s",
        "jade.hopper.locked": "Воронка заблокирована",
        "jade.mobduplication.time": "Перезарядка дублирования: %d с",
        "jade.seconds": "%d с",
        "narration.jade.blockpos": "X%s Y%s Z%s ",
        "narration.jade.distance": "Расстояние %s",
        "narration.jade.negative": "минус %s",
    },
    "jei": {
        "config.jei.advanced.addBookmarksToFront": "Добавлять новые закладки в начало",
        "config.jei.advanced.addBookmarksToFront.comment": "Если включено, новые закладки добавляются в начало списка; если выключено — в конец",
        "jei.key.combo.alt": "ALT + %s",
        "jei.key.combo.command": "CMD + %s",
        "jei.key.combo.control": "CTRL + %s",
        "jei.key.combo.shift": "SHIFT + %s",
        "jei.message.config.folder": "Нажмите, чтобы открыть папку настроек JEI",
        "key.jei.closeRecipeGui": "Закрыть окно рецептов",
    },
    "jeresources": {
        "jer.magmaCream.text": "Малые и большие магмовые кубы",
        "jer.villager.poi": "Рабочее место",
        "jer.worldgen.affectedByFortune": "(Зависит от «Удачи»)",
        "jer.worldgen.chance": "с шансом %s",
    },
    "journeymap": {
        "jm.webmap.topo_button_text": "Рельеф",
        "jm.webmap.topo_button_title": "Топографическая карта мира",
    },
    "loginar": {
        "container.loginar.loginar_urn": "Урна Loginar",
        "container.loginar.lunch_box": "Коробка для обеда",
        "entity.loginar.loginar": "Loginar",
        "key.category.loginar": "Хранилище Loginar",
        "key.loginar.swapUrnItems": "Обменять предметы с урной",
        "misc.loginar.not_implemented": "Ещё не реализовано! Эта функция пока не работает. :(",
        "misc.loginar.swapper.holdingUrn": "Нельзя обменять предметы, держа урну",
        "misc.loginar.swapper.noCompatibleUrn": "Урна с улучшением обмена не найдена",
        "misc.loginar.urn.upgrades": "Улучшения (%s / %s)",
        "subtitles.block.loginar.urn.lid": "Крышка урны Loginar двигается",
        "subtitles.block.loginar.urn.open": "Урна Loginar открывается",
        "subtitles.entity.loginar.attack": "Loginar лает",
        "subtitles.entity.loginar.death": "Loginar погибает",
        "subtitles.entity.loginar.hurt": "Loginar ранен",
        "subtitles.entity.loginar.idle": "Loginar мурлычет",
    },
    "moonlight": {
        "leaves_type.twilightforest.dark": "Тёмное дерево",
        "leaves_type.ulterlands.souldrained": "Окаменевшие",
        "wood_type.twilightforest.dark": "тёмного дерева",
    },
    "moreoverlays": {
        "gui.config.moreoverlays.reset_config": "Сбросить настройки",
        "gui.config.moreoverlays.save": "Сохранить",
        "gui.config.moreoverlays.undo": "Отменить изменения",
    },
    "notenoughcrashes": {
        "notenoughcrashes.crashscreen.noModsErrored": "Ни один мод не указан. Но мод всё равно мог косвенно вызвать сбой.",
        "notenoughcrashes.gui.loadingCrashyUpload": "Отправка…",
        "notenoughcrashes.gui.uploadToCrashy": "Показать на Crashy [бета]",
    },
    "patchouli": {
        "item.patchouli:pamphlet.landing": "Тестовая брошюра — книга всего с одной категорией.",
        "item.patchouli:pamphlet.name": "Тестовая брошюра",
        "patchouli.gui.lexicon.button.toggle_mock_header": "Переключить пробный заголовок",
    },
    "quit": {
        "key.categories.quit": "Выход",
        "key.quit.bossKey": "Тревожная клавиша",
        "key.quit.fastQuit": "Быстрый выход",
        "menu.quit.quitGame": "Выйти из игры?",
        "menu.quit.quitLevel": "Выйти в главное меню?",
    },
    "skyblockbuilder": {
        "skyblockbuilder.command.error.teleport_across_dimensions": "Телепортация между измерениями запрещена.",
        "skyblockbuilder.command.error.teleportation_not_allowed_dimension": "Телепортация в этом измерении запрещена.",
        "skyblockbuilder.command.success.convert_template": "%s преобразован в %s.",
        "skyblockbuilder.item.structure_saver.nbt_to_snbt.tooltip": "Сохранить как файл .snbt",
    },
    "sophisticatedcore": {
        "gui.sophisticatedcore.tooltip.stack_limit": "Лимит: %s",
        "gui.sophisticatedcore.upgrades.chipped_carpenter_workbench": "Плотник",
        "gui.sophisticatedcore.upgrades.chipped_carpenter_workbench.tooltip": "Верстак плотника",
        "gui.sophisticatedcore.upgrades.chipped_glassblower_workbench": "Стеклодув",
        "gui.sophisticatedcore.upgrades.chipped_glassblower_workbench.tooltip": "Верстак стеклодува",
        "gui.sophisticatedcore.upgrades.chipped_mason_workbench": "Каменщик",
        "gui.sophisticatedcore.upgrades.chipped_mason_workbench.tooltip": "Верстак каменщика",
        "gui.sophisticatedcore.upgrades.chipped_philosopher_workbench": "Философ",
        "gui.sophisticatedcore.upgrades.chipped_philosopher_workbench.tooltip": "Верстак философа",
        "gui.sophisticatedcore.upgrades.chipped_shephed_workbench.tooltip": "Верстак пастуха",
        "gui.sophisticatedcore.upgrades.chipped_shepherd_workbench": "Пастух",
        "gui.sophisticatedcore.upgrades.chipped_tinkerer_workbench": "Мастер",
        "gui.sophisticatedcore.upgrades.chipped_tinkerer_workbench.tooltip": "Верстак мастера",
    },
    "trashcans": {
        "trashcans.advancement.trash_can.description": "Создайте мусорную корзину",
        "trashcans.advancement.trash_can.title": "Не забывайте о переработке",
        "trashcans.advancement.ultimate_trash_can.description": "Создайте предельную мусорную корзину",
        "trashcans.advancement.ultimate_trash_can.title": "Предельная мусорная корзина",
        "trashcans.block.energy_trash_can": "Энергетическая мусорная корзина",
        "trashcans.block.item_trash_can": "Предметная мусорная корзина",
        "trashcans.block.liquid_trash_can": "Жидкостная мусорная корзина",
        "trashcans.block.ultimate_trash_can": "Предельная мусорная корзина",
        "trashcans.energy_trash_can.info": "Уничтожает энергию и позволяет ограничить скорость её передачи",
        "trashcans.gui.arrow.left": "Уменьшить лимит энергии",
        "trashcans.gui.arrow.right": "Увеличить лимит энергии",
        "trashcans.item_trash_can.info": "Уничтожает предметы и содержит фильтр на 9 предметов",
        "trashcans.liquid_trash_can.info": "Уничтожает жидкости и газы и содержит фильтр на 9 жидкостей",
        "trashcans.ultimate_trash_can.info": "Уничтожает предметы, жидкости и энергию",
    },
    "untitledduckmod": {
        "untitledduckmod.config.duck_group_size": "Размер группы уток",
        "untitledduckmod.config.duck_group_size.tooltip": "Сколько уток появляется в одной группе",
        "untitledduckmod.config.duck_spawn_weight": "Частота появления уток",
        "untitledduckmod.config.duck_spawn_weight.tooltip": "Как часто появляются утки: чем больше значение, тем чаще",
        "untitledduckmod.config.ducks": "Утки",
        "untitledduckmod.config.geese": "Гуси",
        "untitledduckmod.config.goose_group_size": "Размер группы гусей",
        "untitledduckmod.config.goose_group_size.tooltip": "Сколько гусей появляется в одной группе",
        "untitledduckmod.config.goose_spawn_weight": "Частота появления гусей",
        "untitledduckmod.config.goose_spawn_weight.tooltip": "Как часто появляются гуси: чем больше значение, тем чаще",
        "untitledduckmod.config.title": "Настройки Untitled Duck Mod",
    },
    "fancymenu": {
        "fancymenu.animation.choose": "Выбор анимации",
        "fancymenu.animation.choose.available_animations": "Доступные анимации",
        "fancymenu.animation.choose.no_animation_selected": "§xСначала выберите анимацию!",
        "fancymenu.animation.choose.no_animations": "§xАнимации не найдены!",
        "fancymenu.animation.choose.preview": "Предпросмотр анимации",
        "fancymenu.background.animation": "Анимация",
        "fancymenu.background.animation.configure": "Настройка анимированного фона",
        "fancymenu.background.animation.configure.choose_animation": "Выбрать анимацию",
        "fancymenu.background.animation.configure.no_animation_chosen": "§xСначала выберите анимацию!",
        "fancymenu.background.animation.configure.restart_on_load.off": "Перезапускать анимацию при открытии экрана: §xОтключено",
        "fancymenu.background.animation.configure.restart_on_load.on": "Перезапускать анимацию при открытии экрана: §yВключено",
        "fancymenu.background.animation.desc": "Анимированный фон.\nПодробности: docs.fancymenu.net.",
        "fancymenu.background.image.desc": "Обычное изображение.\nПоддерживает JPEG, PNG, APNG и другие форматы,\nа также локальные файлы и веб-ссылки.",
        "fancymenu.background.slideshow": "Слайд-шоу",
        "fancymenu.customization.items.slider.editor.range.set_max_range_value": "Задать максимальное значение",
        "fancymenu.customization.items.slider.editor.range.set_min_range_value": "Задать минимальное значение",
        "fancymenu.customization.items.slider.editor.set_label_prefix": "Задать префикс подписи",
        "fancymenu.customization.items.slider.editor.set_label_suffix": "Задать суффикс подписи",
        "fancymenu.customization.items.text.scrolling.off": "Прокрутка: §xОтключена",
        "fancymenu.customization.items.text.scrolling.on": "Прокрутка: §yВключена",
        "fancymenu.customization.items.text.shadow.off": "Тень: §xОтключена",
        "fancymenu.customization.items.text.shadow.on": "Тень: §yВключена",
        "fancymenu.customization.items.ticker.async.off": "Асинхронность: §xОтключена",
        "fancymenu.customization.items.ticker.async.on": "Асинхронность: §yВключена",
        "fancymenu.editor.action.screens.add_action.desc": "Добавить новое действие.",
        "fancymenu.editor.action.screens.edit_action": "Изменить",
        "fancymenu.editor.action.screens.edit_action.desc": "Изменить выбранную запись.",
        "fancymenu.editor.action.screens.finish.no_action_selected": "§xСначала выберите действие!",
        "fancymenu.editor.action.screens.remove_action": "Удалить",
        "fancymenu.editor.action.screens.remove_action.confirm": "§x§lВы уверены?\n\nДействительно §xудалить §rвыбранное действие?\nЭто нельзя отменить!",
        "fancymenu.editor.action.screens.remove_action.desc": "Удалить выбранную запись.",
        "fancymenu.editor.actions.execute_terminal_command.edit": "Изменить команды терминала",
        "fancymenu.editor.actions.execute_terminal_command.edit.desc.line1": "Команды задаются отдельно для каждой ОС.",
        "fancymenu.editor.actions.execute_terminal_command.edit.desc.line2": "Действие выполняется только в ОС, для которой задана команда.",
        "fancymenu.editor.actions.execute_terminal_command.edit.desc.line3": "Для неизвестной ОС будет использована команда Linux.",
        "fancymenu.editor.actions.execute_terminal_command.linux": "Команда Linux:",
        "fancymenu.editor.actions.execute_terminal_command.macos": "Команда macOS:",
        "fancymenu.editor.actions.execute_terminal_command.windows": "Команда Windows:",
        "fancymenu.editor.add.animation": "Анимация",
        "fancymenu.editor.add.animation.desc": "Анимация похожа на GIF, но имеет более высокое разрешение.\n\nПодробности: docs.fancymenu.net.",
        "fancymenu.editor.add.slideshow": "Слайд-шоу",
        "fancymenu.editor.custombutton.config.actiontype.copyfile": "Копировать файл или папку",
        "fancymenu.editor.custombutton.config.actiontype.copyfile.desc": "Копирует файл или папку.",
        "fancymenu.editor.custombutton.config.actiontype.copyfile.desc.value": "Путь к файлу или папке + путь назначения [через ';']",
        "fancymenu.editor.custombutton.config.actiontype.deletefile": "Удалить файл или папку",
        "fancymenu.editor.custombutton.config.actiontype.deletefile.desc": "Удаляет файл или папку.",
        "fancymenu.editor.custombutton.config.actiontype.downloadfile": "Скачать файл",
        "fancymenu.editor.custombutton.config.actiontype.downloadfile.desc": "Скачивает файл.",
        "fancymenu.editor.custombutton.config.actiontype.downloadfile.desc.value": "URL + путь назначения [через ';']",
        "fancymenu.editor.custombutton.config.actiontype.mimicbutton.desc": "Имитирует нажатие обычной кнопки Minecraft или другого мода.\n\nНужен §lлокатор кнопки§r. Чтобы получить его, щёлкните кнопку ПКМ в редакторе. Вне редактора включите отладочный оверлей и щёлкните кнопку ПКМ.",
        "fancymenu.editor.custombutton.config.actiontype.mimicbutton.desc.value": "Локатор кнопки",
        "fancymenu.editor.custombutton.config.actiontype.movefile": "Переместить файл или папку",
        "fancymenu.editor.custombutton.config.actiontype.movefile.desc": "Перемещает файл или папку.",
        "fancymenu.editor.custombutton.config.actiontype.movefile.desc.value": "Старый путь + новый путь [через ';']",
        "fancymenu.editor.custombutton.config.actiontype.openfile": "Открыть файл или папку",
        "fancymenu.editor.custombutton.config.actiontype.openfile.desc": "Открывает файл или папку.",
        "fancymenu.editor.custombutton.config.actiontype.openfile.desc.value": "Путь к файлу или папке",
        "fancymenu.editor.custombutton.config.actiontype.quitgame.desc": "Выйти из Minecraft.",
        "fancymenu.editor.custombutton.config.actiontype.renamefile": "Переименовать файл или папку",
        "fancymenu.editor.custombutton.config.actiontype.renamefile.desc": "Переименовывает файл или папку.",
        "fancymenu.editor.custombutton.config.actiontype.renamefile.desc.value": "Путь + новое имя файла или папки [через ';']",
        "fancymenu.editor.custombutton.config.actiontype.runcmd": "Выполнить команду CMD или терминала",
        "fancymenu.editor.custombutton.config.actiontype.runcmd.desc": "Выполняет команду CMD или терминала.\nПоддерживает отдельные команды для разных ОС.",
        "fancymenu.editor.custombutton.config.actiontype.runscript": "Запустить сценарий кнопки",
        "fancymenu.editor.custombutton.config.actiontype.runscript.desc": "Запускает сценарий кнопки.",
        "fancymenu.editor.custombutton.config.actiontype.runscript.desc.value": "Имя файла сценария",
        "fancymenu.editor.custombutton.config.actiontype.unpackzip": "Распаковать ZIP-архив",
        "fancymenu.editor.custombutton.config.actiontype.unpackzip.desc": "Распаковывает ZIP-архив.",
        "fancymenu.editor.custombutton.config.actiontype.unpackzip.desc.value": "Путь к архиву + путь назначения [через ';']",
        "fancymenu.editor.items.button.btndescription.desc": "Подсказка, отображаемая при наведении на элемент.",
        "fancymenu.editor.items.button.clicksound": "Звук нажатия",
        "fancymenu.editor.items.setorientation": "Точка привязки",
        "fancymenu.editor.items.splash.basecolor": "Задать цвет текста",
        "fancymenu.editor.items.splash.bounce.off": "Подпрыгивание: §xОтключено",
        "fancymenu.editor.items.splash.bounce.on": "Подпрыгивание: §yВключено",
        "fancymenu.editor.items.splash.refresh.off": "Обновлять при открытии экрана: §xОтключено",
        "fancymenu.editor.items.splash.refresh.on": "Обновлять при открытии экрана: §yВключено",
        "fancymenu.editor.items.splash.rotation": "Задать поворот",
        "fancymenu.editor.loading_requirement.screens.build_screen.requirement_mode.normal": "Режим условия: §zОБЫЧНЫЙ",
        "fancymenu.editor.loading_requirement.screens.build_screen.requirement_mode.opposite": "Режим условия: §zОБРАТНЫЙ",
        "fancymenu.editor.loading_requirement.screens.manage_screen.edit.generic": "Изменить",
        "fancymenu.editor.loading_requirement.screens.manage_screen.manage": "Управление условиями загрузки",
        "fancymenu.editor.loading_requirement.screens.manage_screen.remove.generic": "Удалить",
        "fancymenu.editor.loading_requirement.screens.remove_group.confirm": "§x§lВы уверены?\n\nДействительно §xудалить §rвыбранную группу?\nЭто действие нельзя отменить!",
        "fancymenu.editor.loading_requirement.screens.remove_requirement.confirm": "§x§lВы уверены?\n\nДействительно §xудалить §rвыбранное условие?\nЭто действие нельзя отменить!",
        "fancymenu.editor.loading_requirement.screens.requirement.info.mode.normal": "Обычный",
        "fancymenu.element.general.appearance_delay.fade_in.off": "Плавное появление: §xОтключено",
        "fancymenu.element.general.appearance_delay.fade_in.on": "Плавное появление: §yВключено",
        "fancymenu.elements.animation.restore_aspect_ratio": "Восстановить соотношение сторон",
        "fancymenu.elements.animation.set_animation": "Задать анимацию",
        "fancymenu.elements.splash.shadow.off": "Тень: §xОтключена",
        "fancymenu.elements.splash.shadow.on": "Тень: §yВключена",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.categories.advanced": "Дополнительно",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.categories.realtime": "Реальное время",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.variables.local.desc": "Переводит текст по заданному ключу.\n\nЗамените 'localization.key' в заполнителе нужным ключом локализации.\n\n§xИнструкции по добавлению переводов: §ldocs.fancymenu.net§r.",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.variables.randomtext": "Случайная строка из TXT-файла",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.variables.randomtext.desc": "Выбирает случайную строку из TXT-файла.\n\nПоддерживает настраиваемый интервал смены строк. Замените 'randomtexts.txt' путём к своему файлу, а '10' — интервалом в секундах. При интервале 0 строка выбирается один раз за сеанс.",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.variables.realtimeday": "День",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.variables.realtimehour": "Час",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.variables.realtimeminute": "Минута",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.variables.realtimemonth": "Месяц",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.variables.realtimesecond": "Секунда",
        "fancymenu.fancymenu.editor.dynamicvariabletextfield.variables.realtimeyear": "Год",
        "fancymenu.guicomponents.reset": "Сбросить",
        "fancymenu.guicomponents.set": "Задать",
        "fancymenu.helper.buttonaction.paste_to_chat.desc": "Вставляет текст в поле чата.",
        "fancymenu.helper.buttonaction.variables.clearall": "Очистить все переменные",
        "fancymenu.helper.buttonaction.variables.clearall.desc": "Удаляет ВСЕ сохранённые переменные.",
        "fancymenu.helper.buttonaction.variables.set": "Задать значение переменной",
        "fancymenu.helper.buttonaction.variables.set.desc": "Сохраняет переменные для использования в заполнителях и условиях загрузки.",
        "fancymenu.helper.editor.element.vanilla.deepcustomization.titlescreen.realmsnotification": "Значок уведомлений Realms",
        "fancymenu.helper.editor.items.buttons.buttonbackground.set": "Задать",
        "fancymenu.helper.editor.items.loadingrequirement.file_exists.desc": "Проверяет существование файла или папки.",
        "fancymenu.helper.editor.items.playerentity.baby.off": "Детёныш: §xНет",
        "fancymenu.helper.editor.items.playerentity.baby.on": "Детёныш: §yДа",
        "fancymenu.helper.editor.items.playerentity.cape.auto.off": "Автовыбор плаща: §xОтключён",
        "fancymenu.helper.editor.items.playerentity.cape.auto.on": "Автовыбор плаща: §yВключён",
        "fancymenu.helper.editor.items.playerentity.copy_client_player.off": "Копировать игрока клиента: §xОтключено",
        "fancymenu.helper.editor.items.playerentity.copy_client_player.on": "Копировать игрока клиента: §yВключено",
        "fancymenu.helper.editor.items.playerentity.crouching.off": "Крадётся: §xНет",
        "fancymenu.helper.editor.items.playerentity.crouching.on": "Крадётся: §yДа",
        "fancymenu.helper.editor.items.playerentity.parrot.off": "Попугай: §xНет",
        "fancymenu.helper.editor.items.playerentity.parrot.on": "Попугай: §yДа",
        "fancymenu.helper.editor.items.playerentity.parrot_left.off": "Попугай на левом плече: §xНет",
        "fancymenu.helper.editor.items.playerentity.parrot_left.on": "Попугай на левом плече: §yДа",
        "fancymenu.helper.editor.items.playerentity.show_name.off": "Показывать имя игрока: §xНет",
        "fancymenu.helper.editor.items.playerentity.show_name.on": "Показывать имя игрока: §yДа",
        "fancymenu.helper.editor.items.playerentity.skin.auto.off": "Автовыбор скина: §xОтключён",
        "fancymenu.helper.editor.items.playerentity.skin.auto.on": "Автовыбор скина: §yВключён",
        "fancymenu.helper.editor.items.playerentity.slim.off": "Тонкая модель: §xНет",
        "fancymenu.helper.editor.items.playerentity.slim.on": "Тонкая модель: §yДа",
        "fancymenu.helper.editor.items.visibilityrequirements.guiscale.desc": "Проверяет текущий масштаб интерфейса.\n\nПоддерживаются больше ('>'), меньше ('<') и точное равенство. Например: '<3.20', '1.0' или '>2.20' (без кавычек).",
        "fancymenu.helper.editor.items.visibilityrequirements.is_any_button_hovered": "Курсор наведён на ЛЮБУЮ кнопку",
        "fancymenu.helper.editor.items.visibilityrequirements.is_any_element_hovered": "Курсор наведён на ЛЮБОЙ элемент",
        "fancymenu.helper.placeholder.get_variable": "Получить сохранённую переменную",
        "fancymenu.helper.placeholder.get_variable.desc": "Возвращает значение сохранённой переменной.\n\nЗамените 'some_variable' настоящим именем переменной.",
        "fancymenu.helper.placeholder.json.desc": "Разбирает JSON и возвращает значение.\n\nЗамените 'path_or_link_to_json' путём или ссылкой на JSON-файл, а '$.some.json.path' — путём JSON до нужного значения.\n\n§zПодробнее о путях JSON: §ljson.fancymenu.net§r§z.",
        "fancymenu.helper.visibilityrequirement.is_variable_value.desc": "Проверяет, равно ли значение сохранённой переменной X. Поддерживаются только собственные переменные FancyMenu, но не переменные других модов или Minecraft.",
        "fancymenu.overlay.menu_bar.user_interface.ui_scale": "Масштаб интерфейса: %s",
        "fancymenu.overlay.menu_bar.user_interface.ui_text_shadow": "Тень текста интерфейса: %s",
    },
}


def english_for(namespace: str) -> dict[str, str]:
    wanted = f"assets/{namespace}/lang/en_us.json"
    merged: dict[str, str] = {}
    for jar in sorted((ROOT / "server/mods").glob("*.jar")):
        try:
            with zipfile.ZipFile(jar) as archive:
                if wanted in archive.namelist():
                    merged.update(json.loads(archive.read(wanted).decode("utf-8-sig")))
        except zipfile.BadZipFile:
            continue
    if merged:
        return merged
    raise SystemExit(f"English language file for {namespace} not found")


def placeholders(value: str) -> Counter[str]:
    return Counter(PLACEHOLDER_RE.findall(value))


def main() -> None:
    for namespace, translations in MANUAL.items():
        english = english_for(namespace)
        unknown = set(translations) - set(english)
        if unknown:
            raise SystemExit(f"Unknown {namespace} keys: {sorted(unknown)}")
        for key, russian in translations.items():
            if placeholders(english[key]) != placeholders(russian):
                raise SystemExit(f"Placeholder mismatch in {key}")
        output = ASSETS / namespace / "lang/ru_ru.json"
        current = json.loads(output.read_text(encoding="utf-8-sig")) if output.exists() else {}
        current.update(translations)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(current, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"{namespace}: applied {len(translations)} reviewed strings")


if __name__ == "__main__":
    main()
