#!/usr/bin/env python3
"""Replace reviewed English fallbacks in otherwise present Russian files."""

from __future__ import annotations

import json
import re
import zipfile
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "overrides/kubejs/assets"
PLACEHOLDER_RE = re.compile(r"%(?:\d+\$)?([a-zA-Z%])")

MANUAL = {
    "blockcarpentry": {
        "block.blockcarpentry.falling_frameblock": "Каркасный блок, подверженный гравитации (в разработке)",
        "block.blockcarpentry.frame_carpet": "Каркасный ковёр",
        "block.blockcarpentry.frame_pane": "Каркасная панель",
        "block.blockcarpentry.frame_daylight_detector": "Каркасный датчик дневного света",
        "block.blockcarpentry.frame_layered_block": "Слоистый каркасный блок",
        "block.blockcarpentry.illusion_carpet": "Иллюзорный ковёр",
        "block.blockcarpentry.illusion_pane": "Иллюзорная панель",
        "block.blockcarpentry.illusion_daylight_detector": "Иллюзорный датчик дневного света",
        "block.blockcarpentry.illusion_layered_block": "Слоистый иллюзорный блок",
        "message.blockcarpentry.light_level": "Уровень освещения: %s",
        "message.blockcarpentry.texture": "Текстура: %s",
        "message.blockcarpentry.design": "Узор: %s",
        "message.blockcarpentry.design_texture": "Текстура узора: %s",
        "message.blockcarpentry.grass_overlay": "Включено травяное покрытие",
        "message.blockcarpentry.grass_overlay_large": "Включено большое травяное покрытие",
        "message.blockcarpentry.snow_overlay_small": "Включено малое снежное покрытие",
        "message.blockcarpentry.snow_overlay": "Включено снежное покрытие",
        "message.blockcarpentry.vine_overlay": "Включено покрытие лианами",
        "message.blockcarpentry.special_overlay": "Включено особое покрытие %s",
        "message.blockcarpentry.rotation": "Текстура повёрнута: %s",
        "message.blockcarpentry.lock": "Этот блок теперь заблокирован!",
        "message.blockcarpentry.unlock": "Блок разблокирован: игроки снова могут его открывать и закрывать!",
        "message.blockcarpentry.block_not_available": "К сожалению, этот блок невозможно отобразить",
        "itemGroup.blockcarpentry": "Столярные блоки",
        "advancements.blockcarpentry.root.description": "Нажмите ПКМ выбранным блоком и наслаждайтесь",
        "advancements.blockcarpentry.illusion_blocks.title": "А в чЁм РаЗнИцА??????",
        "advancements.blockcarpentry.illusion_blocks.description": "Подсказка: создайте на верстаке каркасный и иллюзорный блоки и выясните сами",
        "advancements.blockcarpentry.gathering.title": "Леса лесов",
        "advancements.blockcarpentry.gathering.description": "Теперь у вас официально больше всех строительных лесов в мире и можно зваться лесным королём",
        "advancements.blockcarpentry.stairs.title": "На ступень выше",
        "advancements.blockcarpentry.stairs.description": "Что там наверху? Увы, ступеньки не разговаривают. Поняли? :D",
        "advancements.blockcarpentry.slab.title": "Полушутка",
        "advancements.blockcarpentry.slab.description": "Заходят как-то две бетонные плиты в бар…",
        "advancements.blockcarpentry.door.title": "До чего же дверовательные шутки",
        "advancements.blockcarpentry.door.description": "Уже устали от этих шуток?",
        "advancements.blockcarpentry.button.title": "Кнопка упала с утёса!",
        "advancements.blockcarpentry.button.description": "Почему? Потому что её нажали",
        "advancements.blockcarpentry.trapdoor.title": "Это ловушка!",
        "advancements.blockcarpentry.trapdoor.description": "Как выбраться? Нажмите Escape",
        "advancements.blockcarpentry.bed.title": "Шутки довольно постельные",
        "advancements.blockcarpentry.bed.description": "Смотрите новый ужастик «Рассвет кровати»",
        "advancements.blockcarpentry.fence.title": "В пределах разумного забора",
        "advancements.blockcarpentry.fence.description": "Однажды всё это обретёт совершенный забор",
        "advancements.blockcarpentry.gate.title": "Великий Гэтс-калитка",
        "advancements.blockcarpentry.gate.description": "«За каждым великим калиточником стоит великая калиточница», — однажды сказал мудрый монах",
        "advancements.blockcarpentry.ladder.title": "Как взобраться по лестнице",
        "advancements.blockcarpentry.ladder.description": "Ступень 1: ступень 1\nСтупень 2: ступень 2\nСтупень 3: ступень 3\nСтупень 4: ступень 4",
        "advancements.blockcarpentry.wall.title": "Для всех стен и целей",
        "advancements.blockcarpentry.wall.description": "Лучше сыграю в «Стена долга: современная стеновщина» или «Стенопад 76»",
        "advancements.blockcarpentry.pressure_plate.title": "Страсть, боль и давление",
        "advancements.blockcarpentry.pressure_plate.description": "Новый альбом при участии DJ Нажим и Lil Плиты",
        "advancements.blockcarpentry.chest.title": "Нужно снять груз с сундука",
        "advancements.blockcarpentry.chest.description": "Напомним о Великой ящичной депрессии — на случай, если вы забыли, что было в контейнере",
        "advancements.blockcarpentry.all.title": "Самый §l§n§1к§2р§3а§4с§5и§6в§bы§eй§r земляной дом в мире",
        "advancements.blockcarpentry.all.description": "Только посмотрите на все эти новые возможности",
        "tooltip.blockcarpentry.shift": "§6§oЗажмите §r§2§lSHIFT§r§6§o, чтобы узнать больше",
        "tooltip.blockcarpentry.hammer": "§6§oНажмите ПКМ по каркасному или иллюзорному блоку, чтобы удалить содержимое, не разрушая сам блок",
        "tooltip.blockcarpentry.base_frame": "§6§oУстановите каркас и нажмите по нему ПКМ выбранным блоком: каркас примет его вид и одинаковую текстуру со всех сторон",
        "tooltip.blockcarpentry.base_illusion": "§6§oУстановите иллюзорный блок и нажмите по нему ПКМ выбранным блоком: он полностью примет модель этого блока.\nНапример, модель печи даст настоящие переднюю, боковые, верхнюю и нижнюю грани — отсюда название «иллюзорный блок»",
        "tooltip.blockcarpentry.vanilla_like": "\n§6§oКаркас ведёт себя как ванильный аналог, но не перенимает свойства скопированного блока",
        "tooltip.blockcarpentry.rotatable": "\n§6§oУстанавливайте блок крадучись, чтобы получить вертикальный вариант",
        "tooltip.blockcarpentry.layered": "\n§6§oБлок можно размещать в шести направлениях и складывать слоями, как снег",
        "tooltip.blockcarpentry.slope": "\n§6§oСкос и угловой скос ведут себя как обычные ступени, но имеют больше уровней на блок",
        "tooltip.blockcarpentry.locking": "\n§6§oНажмите ПКМ железным слитком, чтобы зафиксировать открытое или закрытое состояние, либо редстоуновой пылью, чтобы блок игнорировал сигналы редстоуна.\nНажмите ещё раз, чтобы отменить",
    },
    "extendedcrafting": {
        "itemGroup.extendedcrafting": "Расширенный крафт",
        "book.extendedcrafting.name": "Расширенный крафт",
        "book.extendedcrafting.category.crafting.description": "В этом разделе описаны способы крафта, добавленные модом Extended Crafting.",
        "book.extendedcrafting.category.components.description": "В этом разделе описаны компоненты крафта, добавленные модом Extended Crafting.",
        "book.extendedcrafting.category.utilities.name": "Инструменты крафта",
        "book.extendedcrafting.category.utilities.description": "В этом разделе описаны вспомогательные средства крафта, добавленные модом Extended Crafting.",
        "book.extendedcrafting.entry.combination": "Комбинационный крафт",
        "book.extendedcrafting.entry.combination.page.1": "Комбинационный крафт — многоблочная установка в мире, объединяющая предметы во что-то $(italic)особенное.$() $(br2)В центре находится ядро крафта, а вокруг — пьедесталы. Их можно размещать в радиусе 3 блоков от ядра, но обязательно на одной высоте Y.",
        "book.extendedcrafting.entry.combination.page.2": "Для работы ядру крафта нужна энергия. $(br2)Центральный предмет рецепта кладётся на ядро, остальные — на окружающие пьедесталы. $(br)Нажмите ПКМ по боковой стороне ядра, чтобы увидеть ход крафта, расход и запас энергии.",
        "book.extendedcrafting.entry.tables": "Крафт на верстаках",
        "book.extendedcrafting.entry.tables.page.1": "Мод добавляет верстаки разных уровней с сетками $(bold)3×3$(), $(bold)5×5$(), $(bold)7×7$() и $(bold)9×9$(). После закрытия предметы остаются внутри.",
        "book.extendedcrafting.entry.compression": "Компрессионный крафт",
        "book.extendedcrafting.entry.compression.page.1": "Квантовое сжатие — это немного чрезмерное сжатие предметов в квантовом компрессоре. $(br2)Эта энергозависимая машина хранит и сжимает огромные объёмы материалов. Загруженные предметы попадают во внутренний буфер, показанный синей полосой.",
        "book.extendedcrafting.entry.compression.page.2": "Каждому рецепту $(bold)обычно$() нужен катализатор. Он помещается в крайний левый слот и не расходуется. $(br2)Когда в буфере достаточно предметов, машина начинает крафт и только тогда потребляет энергию. $(br2)Чтобы вернуть случайно загруженные предметы, нажмите кнопку извлечения над входным слотом.",
        "book.extendedcrafting.entry.compression.page.3": "Предметы буфера хранятся в бесконечной пустоте и возвращаются только извлечением. При разрушении блока они исчезнут навсегда — будьте осторожны! $(br2)Буфер квантового компрессора вмещает $(bold)миллиарды$() предметов, но по умолчанию принимает лишь нужное рецепту количество. Кнопка замка рядом с буфером отключает лимит.",
        "book.extendedcrafting.entry.ender_crafting": "Эндер-крафт",
        "book.extendedcrafting.entry.ender_crafting.page.1": "Эндер-крафт использует силу ожидания. Установка состоит из эндер-верстака и эндер-альтернаторов. Через альтернаторы верстак получает энергию из пустоты: чем их больше, тем быстрее крафт.",
        "book.extendedcrafting.entry.ender_crafting.page.2": "Эндер-альтернаторы можно размещать вокруг эндер-верстака в $(bold)радиусе 3 блоков$() — даже над ним или под ним!",
        "book.extendedcrafting.entry.auto_tables": "Крафт на автоматических верстаках",
        "book.extendedcrafting.entry.auto_tables.page.1": "Автоматические верстаки — улучшенная версия $(l:crafting/tables)обычных верстаков$(): они автоматически принимают предметы и позволяют извлекать результат трубами. $(br2)Поставьте над верстаком сундук и подавайте предметы в него. Перемещение предметов расходует энергию.",
        "book.extendedcrafting.entry.auto_tables.page.2": "Для подачи предметов выложите рецепт в сетке и сохраните его: нажмите Shift+ЛКМ по одному из трёх слотов рецептов справа вверху. Обычное нажатие выбирает рецепт, Shift+ЛКМ удаляет его. $(br2)Извлекать предметы из верстака можно воронкой или другим совместимым устройством.",
        "book.extendedcrafting.entry.auto_tables.page.3": "Автоматический крафт отключается стрелкой вниз под выходным слотом.",
        "book.extendedcrafting.entry.singularities": "Сингулярности",
        "book.extendedcrafting.entry.singularities.page.1": "Сингулярности — чрезвычайно сжатые материалы. $(bold)Обычно$() их создают в $(l:crafting/compression)квантовом компрессоре$(). $(br2)Сингулярности $(bold)наверняка$() пригодятся для многого — например, для $(l:components/ultimate_singularity)предельной сингулярности$().",
        "book.extendedcrafting.entry.ultimate_singularity": "Предельная сингулярность",
        "book.extendedcrafting.entry.ultimate_singularity.page.1": "Предельную сингулярность $(bold)обычно$() создают на $(l:crafting/tables)предельном верстаке$(). $(br2)В неё $(bold)обычно$() входят все или почти все доступные сингулярности.",
        "book.extendedcrafting.entry.handheld_table": "Переносной верстак",
        "book.extendedcrafting.entry.handheld_table.page.1": "Переносной верстак — это верстак.",
    },
    "fluxnetworks": {
        "tooltip.fluxnetworks.flux_storage_2": "Ёмкость энергии: %s",
        "gui.fluxnetworks.config_copied": "Настройки скопированы",
        "gui.fluxnetworks.config_pasted": "Настройки вставлены",
        "gui.fluxnetworks.label.editingconnections": "Изменение подключений: %d",
        "gui.fluxnetworks.label.detailedview": "Подробный вид сети",
        "gui.fluxnetworks.label.clickabove": "Нажмите %s выше",
        "gui.fluxnetworks.label.playersnetwork": "Сеть игрока %s",
        "gui.fluxnetworks.button.batchselect": "Выбрать предметы",
        "gui.fluxnetworks.slot.mainhand": "Основная рука",
        "gui.fluxnetworks.slot.offhand": "Вторая рука",
        "gui.fluxnetworks.slot.curios": "Слоты Curios",
        "gui.fluxnetworks.security.private": "Личная",
        "gui.fluxnetworks.jei.creatingfluxrecipe": "Создание флакса",
        "gui.fluxnetworks.jei.leftclickhelp": "Нажмите ЛКМ по %s",
        "gui.fluxnetworks.label.selected": "Выбрано предметов: %s",
    },
    "immersiveengineering": {
        "advancement.immersiveengineering.open_manual": "ЧИТАЙ РУКОВОДСТВО",
        "advancement.immersiveengineering.craft_hammer": "МОЛОТИЩЕ!",
        "advancement.immersiveengineering.craft_buzzsaw": "Лесоповал",
        "item.immersiveengineering.shader.name.rosequartz": "Розовый кварц",
        "item.immersiveengineering.shader.name.argo": "Арго",
        "item.immersiveengineering.shader.name.sunstrike": "Солнечный удар",
        "item.immersiveengineering.shader.name.locus": "Локус",
        "item.immersiveengineering.shader.name.felix": "Феликс",
        "item.immersiveengineering.shader.name.sharkface": "Акулья морда",
        "item.immersiveengineering.shader.name.dragonsbreath": "Дыхание дракона",
        "item.immersiveengineering.shader.name.hawk": "Ястреб",
        "item.immersiveengineering.shader.name.eyas": "Птенец ястреба",
        "item.immersiveengineering.shader.name.magnum": "Магнум",
        "item.immersiveengineering.shader.name.fox": "Лиса",
        "item.immersiveengineering.shader.name.vaulttec": "Волт-Тек",
        "item.immersiveengineering.shader.name.sponsor": "Спонсор",
        "item.immersiveengineering.shader.name.massfusion": "Массовый синтез",
        "item.immersiveengineering.shader.name.stormflower": "Цветок бури",
        "item.immersiveengineering.shader.name.milo": "Мило",
        "item.immersiveengineering.shader.name.trident": "Трезубец",
        "item.immersiveengineering.shader.name.chloris": "Хлорида",
        "item.immersiveengineering.shader.name.crescentrose": "Роза Полумесяца",
        "item.immersiveengineering.shader.name.qrow": "Кроу",
        "item.immersiveengineering.shader.name.lususnaturae": "Игра природы",
        "item.immersiveengineering.shader.name.vanguard": "Авангард",
        "item.immersiveengineering.shader.name.regal": "Царственный",
        "item.immersiveengineering.shader.name.harrowed": "Измученный",
        "item.immersiveengineering.shader.name.taken": "Одержимый",
        "item.immersiveengineering.shader.name.ikelos": "ИКЕЛОС",
        "item.immersiveengineering.shader.name.angelsthesis": "Тезис ангела",
        "item.immersiveengineering.shader.name.sutherland": "Сазерленд",
        "item.immersiveengineering.shader.name.exia": "Эксия",
        "item.immersiveengineering.shader.name.crimsonlotus": "Багровый лотос",
        "item.immersiveengineering.shader.name.dominator": "Доминатор",
        "item.immersiveengineering.shader.name.warbird": "Боевая птица",
        "item.immersiveengineering.shader.name.matrix": "Матрица",
        "item.immersiveengineering.shader.name.twili": "Твайли",
        "item.immersiveengineering.shader.name.usurper": "Узурпатор",
        "item.immersiveengineering.shader.name.ancient": "Древний",
        "item.immersiveengineering.shader.name.glacis": "Гласис",
        "item.immersiveengineering.shader.name.phoenix": "Феникс",
        "item.immersiveengineering.shader.name.radiant": "Сияющий",
        "item.immersiveengineering.shader.name.hollow": "Пустой",
        "item.immersiveengineering.shader.name.microshark": "Микроакула",
        "item.immersiveengineering.shader.name.normandy": "Нормандия",
        "item.immersiveengineering.shader.name.omnitool": "Омни-инструмент",
        "item.immersiveengineering.shader.name.kindled": "Разгоревшийся",
        "item.immersiveengineering.shader.name.darkfire": "Тёмное пламя",
        "item.immersiveengineering.shader.name.erruption": "Извержение",
        "item.immersiveengineering.shader.name.terra": "Терра",
        "item.immersiveengineering.shader.name.waaagh": "ВАААГХ!",
        "item.immersiveengineering.shader.name.astartes": "Астартес",
        "item.immersiveengineering.shader.name.netherforged": "Выкованный в Незере",
        "ie.manual.entry.mineral_subtitle": "Рудесно!",
        "desc.immersiveengineering.info.oreDict.on": "Словарь руд: включён",
        "desc.immersiveengineering.info.oreDict.off": "Словарь руд: выключен",
        "desc.immersiveengineering.info.shader.details.vanguard": "Название и расцветка посвящены фракции «Авангард».",
        "desc.immersiveengineering.info.day": "%1$s д",
        "desc.immersiveengineering.info.hour": "%1$s ч",
        "desc.immersiveengineering.info.minute": "%1$s мин",
        "desc.immersiveengineering.info.second": "%1$s с",
    },
    "mekanism": {
        "advancements.mekanism.advanced_qio_drive.title": "Хранилище высокой плотности",
        "constants.mekanism.debug_title": "Отладка Mekanism",
        "death.attack.mekanism.laser.player": "%1$s был испепелён при попытке сбежать от %2$s.",
        "energy.mekanism.forge": "Энергия Forge",
        "energy.mekanism.joules": "Джоуль",
        "energy.mekanism.joules.plural": "Джоули",
        "robit_skin.mekanism.ace": "Асексуальный прайд",
        "robit_skin.mekanism.agender": "Агендерный прайд",
        "robit_skin.mekanism.aro": "Аромантический прайд",
        "robit_skin.mekanism.bi": "Бисексуальный прайд",
        "robit_skin.mekanism.enby": "Небинарный прайд",
        "robit_skin.mekanism.genderfluid": "Гендерфлюидный прайд",
        "robit_skin.mekanism.pan": "Пансексуальный прайд",
        "temperature.mekanism.ambient.short": "Н. У.",
        "advancements.mekanism.advanced_qio_drive.description": "Увеличьте ёмкость накопителя QIO",
        "advancements.mekanism.mekasuit.description": "Защитите себя полным комплектом MekaSuit и Meka-Tool",
        "advancements.mekanism.modification_station.description": "Создайте станцию модификации для улучшения MekaSuit и Meka-Tool",
        "advancements.mekanism.plenisher.description": "Создайте жидкостный заполнитель, чтобы возвращать жидкость в мир!",
        "advancements.mekanism.qio_redstone_adapter.description": "Создайте редстоуновый адаптер QIO",
        "advancements.mekanism.upgraded_mekasuit.description": "Установите максимум модулей в MekaSuit и Meka-Tool",
        "description.mekanism.qio_drive_array": "Основа системы квантового управления предметами — QIO. Здесь хранятся накопители QIO.",
        "info.mekanism.jei.module_installation": "Станция модификации устанавливает модули на разные части MekaSuit и на Meka-Tool.",
        "generic.mekanism.mb": "%1$s мБ",
        "generic.mekanism.per_mb": "%1$s/мБ",
        "generic.mekanism.per_tick": "%1$s/т",
        "generic.mekanism.stored.mb": "%1$s: %2$s мБ",
        "network.mekanism.mb_per_tick": "%1$s мБ/т",
        "network.mekanism.mb_stored": "%1$s (%2$s мБ)",
        "tooltip.mekanism.jei.amount.with.capacity": "%1$s / %2$s мБ",
    },
    "jei": {
        "description.jei.wooden.door.1": "Деревянные двери не позволяют монстрам войти в здание.\nТестовые предложения.",
        "description.jei.wooden.door.2": "Нажатие на дверь переключает её между открытым и закрытым состояниями.",
        "description.jei.wooden.door.3": "Деревянные двери можно открывать и закрывать сигналом редстоуна.",
        "description.jei.debug.formatting.1": "Проверка замены форматирования: %s.",
        "description.jei.debug.formatting.2": "Проверка замены форматирования: %s %s.",
        "description.jei.debug.formatting.3": "%s внутри",
    },
    "supplementaries": {
        "block.supplementaries.tater_in_a_jar": "Картофелина в банке",
    },
    "fancymenu": {
        "fancymenu.editor.actions.blocks.if": "ЕСЛИ (%s)",
        "fancymenu.editor.actions.blocks.else_if": "ИНАЧЕ-ЕСЛИ (%s)",
        "fancymenu.editor.actions.blocks.else": "ИНАЧЕ",
        "fancymenu.placeholders.jvm_name": "Виртуальная машина Java",
        "fancymenu.placeholders.jvm_name.desc": "Название виртуальной машины Java.",
        "fancymenu.elements.image.nine_slice": "Девятисегментная текстура: %s",
        "fancymenu.elements.image.nine_slice.border_x": "Границы девятисегментной текстуры по X (слева и справа)",
        "fancymenu.elements.image.nine_slice.border_y": "Границы девятисегментной текстуры по Y (сверху и снизу)",
        "fancymenu.elements.slider.v2.handle.textures.nine_slice": "Свой девятисегментный бегунок: %s",
        "fancymenu.elements.slider.v2.handle.textures.nine_slice.border_x": "Границы девятисегментного бегунка по X (слева и справа)",
        "fancymenu.elements.slider.v2.handle.textures.nine_slice.border_y": "Границы девятисегментного бегунка по Y (сверху и снизу)",
        "fancymenu.helper.editor.items.buttons.textures.nine_slice": "Своя девятисегментная подложка: %s",
        "fancymenu.helper.editor.items.buttons.textures.nine_slice.border_x": "Границы девятисегментной подложки по X (слева и справа)",
        "fancymenu.helper.editor.items.buttons.textures.nine_slice.border_y": "Границы девятисегментной подложки по Y (сверху и снизу)",
    },
    "ftblibrary": {
        "gui.server_forced": "Принудительно задано сервером: %s",
    },
    "ae2wtlib": {
        "itemGroup.ae2wtlib.general": "Беспроводные терминалы AE2 (AE2WTLib)",
        "itemGroup.ae2wtlib": "Беспроводные терминалы AE2 (AE2WTLib)",
        "text.autoconfig.de/mari_023/ae2wtlib.title": "Беспроводные терминалы AE2",
    },
    "buildinggadgets": {
        "itemGroup.buildinggadgets": "Строительные инструменты",
        "key.buildinggadgets.category": "Строительные инструменты",
    },
    "itemfilters": {
        "itemGroup.itemfilters.main": "Фильтры предметов",
        "itemGroup.itemfilters.itemfilters": "Фильтры предметов",
        "item.itemfilters.always_true": "Фильтр «Всегда истина»",
        "item.itemfilters.always_false": "Фильтр «Всегда ложь»",
    },
    "ironchest": {
        "itemGroup.ironchest": "Железные сундуки",
    },
    "decorative_blocks": {
        "itemGroup.decorative_blocks.general": "Декоративные блоки",
    },
    "craftingtweaks": {
        "key.categories.craftingtweaks": "Настройки крафта",
    },
    "energymeter": {
        "itemGroup.energymeter": "Измеритель энергии",
    },
    "elevatorid": {
        "itemGroup.elevators_tab": "Лифты",
    },
    "deeperdarker": {
        "itemGroup.deeperdarker": "Глубже и темнее",
    },
    "neverenderore": {
        "itemGroup.neverenderore": "Бесконечные эндер-руды",
    },
    "moreoverlays": {
        "key.moreoverlays.category": "Обновлённые оверлеи",
    },
    "vanillaplustools": {
        "itemGroup.vanillaplustools": "Инструменты Vanilla+",
    },
    "skyguis": {
        "itemGroup.skyguis": "Небесные интерфейсы",
    },
    "geckolib3": {
        "itemGroup.geckolib_examples": "Примеры GeckoLib",
    },
    "engineersdecor": {
        "block.engineersdecor.dense_grit_sand_block.help": "Спрессованный песчаный грунт с каменной крошкой, как на промышленных и складских площадках.\nЦветы на нём почти не растут. Варианты текстуры зависят от положения.",
        "block.engineersdecor.factory_placer.help": "Размещает блоки и сажает растения или деревья.\nНастройки редстоуна: обычный или инвертированный сигнал (по умолчанию); импульсный или непрерывный режим (по умолчанию).\nТакже умеет высаживать ростки снизу через почву. Неподходящие предметы выбрасывает.",
    },
    "tombstone": {
        "stat.tombstone.trade_grave_guardian": "Обмены с хранителем могилы",
        "tombstone.advancement.stolen_magic.desc": "Вы украли эффект с помощью «Волшебного сифона»",
        "tombstone.advancement.magic_siphoner.desc": "Вы украли 10 эффектов с помощью «Волшебного сифона»",
        "tombstone.advancement.master_siphoner.desc": "Вы украли 50 эффектов с помощью «Волшебного сифона»",
        "tombstone.config.plague_bringer_enchanting_table.tooltip": "Разрешает чары «Чумной вестник» на столе зачарований",
        "tombstone.config.frostbite_enchanting_table.tooltip": "Разрешает чары «Обморожение» на столе зачарований",
        "tombstone.compendium.spectral_bite.desc": "При получении удара есть шанс наложить на атакующего «Спектральный укус».",
        "tombstone.compendium.plague_bringer.desc": "Каждый удар по существу может наложить случайный вредный эффект.\nЕсли мировоззрение владельца не злое, эффект воздействует и на него — это настраивается.\nЧары несовместимы с «Волшебным сифоном».",
        "tombstone.compendium.familiar_receptacle.desc": "Сосуд захватывает душу умершего питомца и все его вещи.\nЗатем душа восстанавливается, медленно поглощая жизненную сущность носителя.\nОбычно питомца возвращают к жизни молитвой с Анхом.\nНа выделенном сервере сосуд может захватить душу, даже если вы не в сети.",
        "tombstone.compendium.impregnated_diamond.desc": "Пропитанный алмаз — ингредиент для создания некоторых сосудов.\nЕго можно объединить с пропитанной костяной иглой.",
    },
    "sophisticatedcore": {
        "item.sophisticatedcore.storage.tooltip.fluid": "%s мБ %s",
    },
    "mekanismtools": {
        "tooltip.mekanismtools.hp": "ОЗ: %1$s",
    },
    "quark": {
        "quark.subtitles.do_it": "СДЕЛАЙ ЭТО",
    },
    "titanium": {
        "itemGroup.resources": "Titanium: ресурсы",
    },
    "journeymap": {
        "jm.advanced.chunk_caching": "Кэширование данных чанков",
        "jm.advanced.chunk_caching.tooltip": "Включает кэширование чанков. Если оно отключено, при телепортации или создании меток за пределами дальности прорисовки будет использоваться уровень моря Minecraft: Y=64.",
        "jm.advanced.gl_error_check": "Проверка ошибок GL",
        "jm.advanced.gl_error_check.tooltip": "Включает проверку ошибок GL. Это может снизить производительность; после изменения требуется перезапуск.",
        "jm.advanced.seed_id": "Поддержка нескольких миров",
        "jm.advanced.seed_id.tooltip": "Экспериментальная поддержка нескольких миров предотвращает перезапись карт на серверах с несколькими мирами.\n\nВНИМАНИЕ: применяется только после повторного входа на сервер!",
        "jm.common.addon_options": "Настройки дополнений",
        "jm.common.addon_options_invalid": "Дополнения с настройками не найдены",
        "jm.common.client_options": "Настройки клиента",
        "jm.common.automap_region_complete": "Нанесено на карту",
        "jm.common.automap_dialog_summary_2": "«Смешивание листвы», «смешивание травы» и «смешивание воды».",
        "jm.common.automap_stop_title": "Остановить автокартографирование",
        "jm.common.birthday": "С днём рождения, %1$s!",
        "jm.common.entity_display.dots": "Точки",
        "jm.common.entity_display.icons": "Значки",
        "jm.common.fullscreen_drag_scale": "Скорость перетаскивания",
        "jm.common.fullscreen_drag_scale.tooltip": "Настраивает скорость перетаскивания: чем больше число, тем медленнее движение. Полезно при системном масштабировании экрана, особенно на дисплеях Retina в macOS.",
        "jm.common.grid_style_region": "Регионы",
        "jm.common.grid_style_squares_region": "Квадраты и регионы",
        "jm.common.map_style_biome": "Карта биомов",
        "jm.common.map_style_biome.tooltip": "Отображает карту биомов.",
        "jm.common.map_style_biomewatercolor": "Цвет воды по биому",
        "jm.common.map_style_biomewatercolor.tooltip": "Окрашивает воду в зависимости от биома.",
        "jm.common.minimap_options.title": "Положение мини-карты: перетаскивайте выбранный элемент мышью или клавишами со стрелками.",
        "jm.common.minimap_position.button": "Положение",
        "jm.common.minimap_position.button.tooltip": "Изменить расположение мини-карты и значков эффектов",
        "jm.common.radar_hide_spectators": "Скрывать наблюдателей",
        "jm.common.radar_hide_spectators.tooltip": "Скрывает наблюдателей на радаре.",
        "jm.common.render.clear_caves": "Прозрачные неосвещённые пещеры",
        "jm.common.render.clear_caves.tooltip": "Неосвещённые блоки и блоки внутри среза отображаются прозрачными, а не чёрными. Действует только на новые участки карты.",
        "jm.common.show_mouse_loc": "Координаты под курсором",
        "jm.common.show_mouse_loc.tooltip": "Показывает над кнопками координаты блока под курсором.",
        "jm.common.show_player_loc": "Координаты игрока",
        "jm.common.show_player_loc.tooltip": "Показывает координаты игрока под верхними кнопками.",
        "jm.common.show_region": "Показывать регионы",
        "jm.common.splash_artist": "Автор",
        "jm.common.system_time_format": "Формат системного времени",
        "jm.common.system_time_format.tooltip": "Формат времени для информационного поля «Системное время»",
        "jm.common.time_format": "Формат реального игрового времени",
        "jm.common.time_format.tooltip": "Формат времени для информационного поля «Реальное игровое время»",
        "jm.common.waypoint.create_packet": "§eJourneyMap:§f сервер создал метку %s в точке [%d, %d, %d], измерение %s",
        "jm.common.waypoint.delete_packet": "§eJourneyMap:§f сервер удалил метку %s.",
        "jm.config.category.minimap_position": "Настройки положения мини-карты",
        "jm.config.category.minimap_position.tooltip": "Настройка расположения и отображения мини-карты и значков эффектов.",
        "jm.fullscreen.map_biome": "Биом",
        "jm.fullscreen.search": "Открыть поиск места",
        "jm.fullscreen.search_execute": "Перейти к месту",
        "jm.hud.effects.anchor": "Привязать значки эффектов",
        "jm.hud.effects.anchor.tooltip": "Привязывает значки эффектов к мини-карте.",
        "jm.hud.effects.enable": "Перемещать значки эффектов",
        "jm.hud.effects.enable.tooltip": "Позволяет переместить значки эффектов зелий от мини-карты.",
        "jm.hud.effects.style.reverse": "Обратный порядок значков эффектов",
        "jm.hud.effects.style.reverse.tooltip": "Отображает значки в обратном порядке: вертикально снизу вверх, горизонтально справа налево.",
        "jm.hud.effects.style.vertical": "Вертикальные значки эффектов",
        "jm.hud.effects.style.vertical.tooltip": "Сначала размещает значки вертикально сверху вниз.",
        "jm.hud.minimap.key_movement_speed": "Шаг перемещения мини-карты клавишами",
        "jm.hud.minimap.key_movement_speed.tooltip": "Количество пикселей за одно нажатие стрелки при точной настройке положения мини-карты.",
        "jm.minimap.info_slot.background_alpha": "Прозрачность фона информационного поля",
        "jm.minimap.info_slot.background_alpha.tooltip": "Настраивает прозрачность фона информационного поля.",
        "jm.minimap.mob_display_scale": "Масштаб существ",
        "jm.minimap.mob_display_scale.tooltip": "Масштаб значков и точек существ.",
        "jm.minimap.player_display": "Отображение игроков",
        "jm.minimap.player_display.tooltip": "Показывает игроков значками или цветными точками.",
        "jm.minimap.player_display_scale": "Масштаб игроков",
        "jm.minimap.player_display_scale.tooltip": "Масштаб значков и точек игроков.",
        "jm.minimap.position_custom": "Произвольное",
        "jm.minimap.position_x": "Положение мини-карты по X",
        "jm.minimap.position_x.tooltip": "Координата X произвольного положения мини-карты в процентах.",
        "jm.minimap.position_y": "Положение мини-карты по Y",
        "jm.minimap.position_y.tooltip": "Координата Y произвольного положения мини-карты в процентах.",
        "jm.minimap.self_display_scale": "Масштаб собственного значка",
        "jm.minimap.self_display_scale.tooltip": "Масштаб значка вашего игрока.",
        "jm.minimap.terrain_background_alpha": "Прозрачность фона карты",
        "jm.minimap.terrain_background_alpha.tooltip": "Настраивает непрозрачность фона карты в процентах.",
        "jm.minimap.waypointicon_scale": "Масштаб значков меток",
        "jm.minimap.waypointicon_scale.tooltip": "Масштаб значков меток.",
        "jm.minimap.waypointlabel_scale": "Масштаб подписей меток",
        "jm.minimap.waypointlabel_scale.tooltip": "Масштаб шрифта подписей меток.",
        "jm.options.multiplayer.button_label": "Сетевая игра",
        "jm.options.multiplayer.category.radar": "Настройки радара",
        "jm.options.multiplayer.category.radar.tooltip": "Настраивает видимость вашего игрока на картах других игроков. Действует только при включённом расширенном радаре.",
        "jm.options.multiplayer.radar.hide_self_underground": "Скрывать себя под землёй",
        "jm.options.multiplayer.radar.hide_self_underground.tooltip": "Не позволяет другим видеть вас, когда вы находитесь под землёй.",
        "jm.options.multiplayer.radar.visible": "Виден другим",
        "jm.options.multiplayer.radar.visible.tooltip": "Выключите, чтобы скрыться с карт других игроков. Операторы по-прежнему смогут вас видеть.",
        "jm.options.multiplayer.title": "Настройки сетевой игры",
        "jm.server.allow_death_points": "Разрешить метки смерти",
        "jm.server.allow_death_points.tooltip": "Разрешает создавать метку при смерти игрока.",
        "jm.server.allow_in_game_beacons": "Разрешить маяки меток",
        "jm.server.allow_in_game_beacons.tooltip": "Разрешает отображать маяки меток в мире. Метки на карте при этом не отключаются.",
        "jm.server.allow_journeymap": "Разрешить JourneyMap",
        "jm.server.allow_journeymap.tooltip": "Разрешает использовать JourneyMap игрокам без прав оператора.",
        "jm.server.allow_view_server_prop": "Разрешить просмотр настроек сервера",
        "jm.server.allow_view_server_prop.tooltip": "Позволяет игрокам без прав оператора просматривать экран администрирования сервера без возможности изменений.",
        "jm.server.allow_waypoints": "Разрешить метки",
        "jm.server.allow_waypoints.tooltip": "Разрешает метки. При отключении полностью скрывает метки и маяки на карте и в мире, а также связанные с ними экраны.",
        "jm.server.button.no_permission.tooltip": "Недостаточно прав!",
        "jm.server.button.no_server.tooltip": "JourneyMap не установлен на сервере!",
        "jm.server.button.save.read_only": "Доступ только для чтения.",
        "jm.server.edit.button.close": "Закрыть",
        "jm.server.edit.chkbox.enable": "Включить",
        "jm.server.edit.chkbox.enable.tooltip": "[Вкл./выкл.]: отдельные настройки этого измерения переопределяют общие.",
        "jm.server.edit.chkbox.teleport": "Телепортация по меткам",
        "jm.server.edit.chkbox.teleport.tooltip": "[Вкл./выкл.]: разрешает или запрещает телепортацию через диспетчер меток.\nЕсли выключено, нельзя телепортироваться в это измерение, из него и внутри него.\nЕсли включено, можно телепортироваться внутри него и в другие измерения с разрешённой телепортацией.",
        "jm.server.edit.chkbox.world.id": "ID мира",
        "jm.server.edit.chkbox.world.id.tooltip": "[Вкл./выкл.]: изменяет папку сохранения картографических данных этого сервера.\nГлавное назначение — избежать перезаписи карт и настроек на серверах с несколькими мирами или одинаковыми именами.\nВНИМАНИЕ: включение на уже работающем сервере после отключения сбросит картографические данные пользователей.",
        "jm.server.edit.fullscreen_server_biomes": "Биомы на полноэкранной карте",
        "jm.server.edit.fullscreen_server_biomes.tooltip": "Позволяет узнавать биом под курсором на полноэкранной карте, как в одиночной игре.",
        "jm.server.edit.hide_ops": "Скрывать операторов",
        "jm.server.edit.hide_ops.tooltip": "Скрывает операторов на радаре при включённом расширенном радаре.",
        "jm.server.edit.label.admin.edit": "Администрирование сервера",
        "jm.server.edit.label.admin.read_only": "Администрирование сервера: только чтение",
        "jm.server.edit.label.selection.default": "Настройки измерений по умолчанию",
        "jm.server.edit.label.selection.default.tooltip": "Эти настройки будут использоваться для всех новых измерений.",
        "jm.server.edit.label.selection.dimension": "Измерение: %1$s",
        "jm.server.edit.label.selection.dimension.tooltip": "Если включено, эти параметры переопределяют общие.",
        "jm.server.edit.label.selection.global": "Общие настройки",
        "jm.server.edit.label.selection.global.tooltip": "Параметры сервера по умолчанию. Включите отдельные настройки измерения, чтобы переопределить общие.",
        "jm.server.edit.mapping.label": "Настройки картографирования",
        "jm.server.edit.mapping.label.tooltip": "Точная настройка доступных игрокам режимов картографирования.",
        "jm.server.edit.mapping.toggle.biome": "Картографирование биомов",
        "jm.server.edit.mapping.toggle.biome.tooltip": "Картографирование биомов: для всех, операторов или никого.",
        "jm.server.edit.mapping.toggle.cave": "Картографирование пещер",
        "jm.server.edit.mapping.toggle.cave.tooltip": "Картографирование пещер: для всех, операторов или никого.",
        "jm.server.edit.mapping.toggle.surface": "Картографирование поверхности",
        "jm.server.edit.mapping.toggle.surface.tooltip": "Картографирование поверхности: для всех, операторов или никого.",
        "jm.server.edit.mapping.toggle.topo": "Топографическое картографирование",
        "jm.server.edit.mapping.toggle.topo.tooltip": "Топографическое картографирование: для всех, операторов или никого.",
        "jm.server.edit.option.all": "Все",
        "jm.server.edit.option.none": "Никто",
        "jm.server.edit.option.op": "Операторы",
        "jm.server.edit.radar": "Общие настройки радара",
        "jm.server.edit.radar.chkbox.animal": "Радар животных",
        "jm.server.edit.radar.chkbox.animal.tooltip": "[Вкл./выкл.]: могут ли игроки видеть животных на карте.",
        "jm.server.edit.radar.chkbox.mob": "Радар враждебных существ",
        "jm.server.edit.radar.chkbox.mob.tooltip": "[Вкл./выкл.]: могут ли игроки видеть монстров и других враждебных существ на карте.",
        "jm.server.edit.radar.chkbox.player": "Радар игроков",
        "jm.server.edit.radar.chkbox.player.tooltip": "[Вкл./выкл.]: могут ли игроки видеть друг друга на карте.",
        "jm.server.edit.radar.chkbox.villager": "Радар жителей",
        "jm.server.edit.radar.chkbox.villager.tooltip": "[Вкл./выкл.]: могут ли игроки видеть жителей на карте.",
        "jm.server.edit.radar.tooltip": "Все: радар работает у всех; отдельные типы можно отключить флажками.\nОператоры: радар полностью отключён для остальных игроков; флажки действуют для операторов.\nНикто: радар отключён у всех.",
        "jm.server.edit.slider.update": "Тиков между обновлениями игроков",
        "jm.server.edit.slider.update.tooltip": "Как часто сервер отправляет обновления координат игроков.",
        "jm.server.edit.toggle.base.all": "[Все]: функция доступна всем.",
        "jm.server.edit.toggle.base.none": "[Никто]: функция отключена для всех.",
        "jm.server.edit.toggle.base.op": "[Операторы]: функция доступна только операторам и администраторам.",
        "jm.server.edit.tracking": "Расширенный радар",
        "jm.server.edit.tracking.tooltip": "Если радар игроков включён, сервер отслеживает игроков за пределами дальности клиента.\nИгроки видят друг друга на карте на любом расстоянии в пределах одного измерения.\nЕсли расширенный радар включён, а радар игроков отключён, функция не работает.\nЕсли расширенный радар отключён, а радар игроков включён, остаётся только радар поблизости.",
        "jm.server.edit.tracking.update.label": "Интервал обновления",
        "jm.server.multiplayer_settings": "Настройки сетевой игры",
        "jm.server.multiplayer_settings.tooltip": "Кому доступно меню сетевой игры: всем, операторам или никому.",
        "jm.server.radar_hide_spectators": "Скрывать наблюдателей",
        "jm.server.radar_hide_spectators.tooltip": "Скрывает наблюдателей на радаре.",
        "jm.server.render_range": "Максимальная дальность прорисовки карты",
        "jm.server.render_range.tooltip": "Ограничивает для всех игроков дальность прорисовки карты в чанках. 0 — использовать настройки клиента.\nПараметр только ограничивает максимум и не увеличивает дальность.\nЭто значение не отображается в разделе «Картография» настроек клиента.",
        "jm.server.see_underground_players": "Видимость игроков под землёй",
        "jm.server.see_underground_players.tooltip": "Только для расширенного радара!\nОпределяет видимость подземных игроков на радаре.\nНа Нижний мир не влияет.\nВСЕ: подземных игроков видят все.\nОПЕРАТОРЫ: только операторы.\nНИКТО: никто.",
        "jm.theme.labelsource.dimension": "Измерение",
        "jm.theme.labelsource.gametime.night": "Ночь",
        "jm.theme.labelsource.gametime.real": "Реальное игровое время",
        "jm.theme.labelsource.gametime.real.tooltip": "Показывает игровое время так, будто восход наступает в 6 утра, а не в полночь.",
        "jm.theme.labelsource.lightlevel": "Уровень освещения",
        "jm.theme.labelsource.moonphase": "Фаза Луны",
        "jm.theme.labelsource.moonphase.day": "День",
        "jm.theme.labelsource.moonphase.first_quarter": "Первая четверть",
        "jm.theme.labelsource.moonphase.full_moon": "Полнолуние",
        "jm.theme.labelsource.moonphase.new_moon": "Новолуние",
        "jm.theme.labelsource.moonphase.pre": "Фаза Луны: ",
        "jm.theme.labelsource.moonphase.third_quarter": "Последняя четверть",
        "jm.theme.labelsource.moonphase.waning_crescent": "Убывающий серп",
        "jm.theme.labelsource.moonphase.waning_gibbous": "Убывающая Луна",
        "jm.theme.labelsource.moonphase.waxing_crescent": "Растущий серп",
        "jm.theme.labelsource.moonphase.waxing_gibbous": "Растущая Луна",
        "jm.theme.labelsource.region": "Регион",
        "jm.waypoint.auto_deathpoint_remove_distance": "Дистанция автоудаления метки смерти",
        "jm.waypoint.auto_deathpoint_remove_distance.tooltip": "Расстояние, на котором удаляется метка смерти. Минимум 2, иначе она исчезнет сразу после создания.",
        "jm.waypoint.auto_remove_deathpoints": "Автоматически удалять метки смерти",
        "jm.waypoint.auto_remove_deathpoints.tooltip": "Автоматически удаляет метки смерти при приближении к ним.",
        "jm.waypoint.command.reloaded": "Метки перезагружены",
        "jm.waypoint.create_temp_waypoint": "Временная метка",
        "jm.waypoint.death_date_format": "Формат даты смерти",
        "jm.waypoint.death_date_format.tooltip": "Формат даты для меток смерти.",
        "jm.waypoint.death_time_format": "Формат времени смерти",
        "jm.waypoint.death_time_format.tooltip": "Формат времени для меток смерти.",
        "jm.waypoint.deviation_button_sort": "Отклонение",
        "jm.waypoint.disable": "Отключить",
        "jm.waypoint.double_click_create": "Двойное нажатие создаёт метку",
        "jm.waypoint.double_click_create.tooltip": "Двойное нажатие на полноэкранной карте создаёт метку в выбранной точке.",
        "jm.waypoint.hide_all": "Скрыть все",
        "jm.waypoint.manager.disable_strikethrough": "Не зачёркивать текст",
        "jm.waypoint.manager.disable_strikethrough.tooltip": "Отключает зачёркивание текста меток.",
        "jm.waypoint.manager.focus_dim": "Открывать диспетчер в текущем измерении",
        "jm.waypoint.manager.focus_dim.tooltip": "Открывает диспетчер меток в текущем измерении.",
        "jm.waypoint.shader": "Шейдеры для маяков",
        "jm.waypoint.shader.tooltip": "Разрешает шейдерам обрабатывать маяки меток. Результат может быть неожиданным.",
        "jm.waypoint.show_all": "Показать все",
        "jm.waypoint.show_death_point_label_on_map": "Показывать подпись метки смерти на карте",
        "jm.waypoint.show_death_point_label_on_map.tooltip": "Управляет подписью метки смерти на полноэкранной и мини-карте.",
        "jm.waypoint.show_deviation": "Показывать отклонение",
        "jm.waypoint.show_deviation.tooltip": "Показывает отклонение направления между игроком и меткой.",
        "jm.waypoint.teleport_command": "Своя команда телепортации к метке",
        "jm.waypoint.teleport_command.tooltip": "Задаёт команду телепортации для сервера. Доступные подстановки: имя игрока — {name}; координаты метки — {x} {y} {z}; целевое измерение — {dim}.",
        "jm.waypoint.temp": "Временная: ",
        "jm.waypoint.temp_waypoint_remove_distance": "Дистанция удаления временной метки",
        "jm.waypoint.temp_waypoint_remove_distance.tooltip": "Расстояние до игрока, на котором временная метка автоматически удаляется.",
        "key.journeymap.fullscreen.disable_buttons": "Скрыть кнопки полноэкранной карты",
        "key.journeymap.fullscreen.menu.chat_position": "Положение чата",
        "key.journeymap.minimap_toggle_alt": "Показать или скрыть мини-карту",
        "key.journeymap.toggle_waypoints": "Показать или скрыть все метки",
    },
    "questsadditions": {
        "ftbquests.task.questsadditions.time.gameTime.tooltip": "Прошедшее время вычисляется так:\nИгра — внутренние игровые часы.\nСистема — время компьютера.\nАвто — игровые часы на сервере, системное время в остальных случаях.",
    },
}


def english_for(namespace: str) -> dict[str, str]:
    wanted = f"assets/{namespace}/lang/en_us.json"
    merged: dict[str, str] = {}
    for jar in sorted((ROOT / "server/mods").glob("*.jar")):
        try:
            with zipfile.ZipFile(jar) as archive:
                if wanted in archive.namelist():
                    merged.update(json.loads(archive.read(wanted).decode("utf-8-sig")))
        except zipfile.BadZipFile:
            continue
    if merged:
        return merged
    raise SystemExit(f"English language file for {namespace} not found")


def placeholders(value: str) -> Counter[str]:
    return Counter(PLACEHOLDER_RE.findall(value))


def main() -> None:
    for namespace, translations in MANUAL.items():
        english = english_for(namespace)
        unknown = set(translations) - set(english)
        if unknown:
            raise SystemExit(f"Unknown {namespace} keys: {sorted(unknown)}")
        for key, russian in translations.items():
            if placeholders(english[key]) != placeholders(russian):
                raise SystemExit(f"Placeholder mismatch in {key}")
        output = ASSETS / namespace / "lang/ru_ru.json"
        current = json.loads(output.read_text(encoding="utf-8-sig")) if output.exists() else {}
        current.update(translations)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(current, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"{namespace}: replaced {len(translations)} English fallbacks")


if __name__ == "__main__":
    main()
